### ISSUE TITLE
Update plot on data changed

### ISSUE THREAD

**Issue by vmora** [ghtmtt/DataPlotly#116]
I'm using DataPlotly with a plugin that will allows user to click on a point on the map to see time series at this point.

The source of the plot is a layer with 3 attributes: time, point_id, value

The click on the map changes the layer filter on point_id (got the idea from TimeManager plugin).

Refreshing the plot when the source layer data is changed would be a nice addition IMO.

I'll PR if I succeed.

**Comment by ghtmtt** [comment]
Hi. Well that would be a great addition! I'm also ccing @nyalldawson. 

So basically you are going to add a button or something similar to the dataplotly UI that allows this functionality?

**Comment by vmora** [comment]
> So basically you are going to add a button or something similar to the dataplotly UI that allows this functionality?

@ghtmtt no, I'm not going to add a button because the ergonomics is really specific to the use case (i.e. the way I set the filter with my custom map tool). 

What I'm adding is a refresh of the plots on layer dataChanged signal this is really generic I believe and would also update the plot if data is edited instead of the filter changed.

**Comment by nyalldawson** [comment]
@vmora 
> What I'm adding is a refresh of the plots on layer dataChanged signal this is really generic I believe and would also update the plot if data is edited instead of the filter changed.

Actually dataChanged **isn't** fired when a layer is edited (counter-intuitive, I know!). But the same update slot could be connected to the QgsVectorLayer.layerModified, which is fired when edits are made to a layer.
