### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by cordrey** [ghtmtt/DataPlotly#123]
Have tried different QGIS versions and data and still unable to run any plots. Always results in error:

stack trace:
```
AttributeError: 'NoneType' object has no attribute 'group' 
Traceback (most recent call last):
  File "/Users/GS/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_dialog.py", line 1045, in createPlot
    self.plot_path = self.plotobject.buildFigures(self.ptype, pl)
  File "/Users/GS/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_plot.py", line 734, in buildFigures
    substr = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Update:  looks like the error is caused by my setup and my guess is it is the python install?  Tried on a win10 box and works fine.  The problem setup is:

OSX 10.14.5 Mojave
Python 3.6.8 :: Anaconda custom (64-bit)
QGIS  3.4.8
Data Plotly 2.3

Update 2:  The python QGIS was using was 3.6.4 and not 3.6.8 so will see if I  still have problem after installing updated python version

Updated python to 3.6.8 (confirmed in qgis python console) and same error is still occurring.

**Comment by ghtmtt** [comment]
Are you using some specific data? I cannot confirm your issue. Could you share the data so I can it a try?

**Comment by cordrey** [comment]
Attached is some sample data.  I am using latitude as x axis values and bathymetry_m as y values.  I have tried numerous similar data sets and get the same issue on OSX  but all work fine with my windows installation.  

[bathytest_SD.txt](https://github.com/ghtmtt/DataPlotly/files/3350434/bathytest_SD.txt)

**Comment by ghtmtt** [comment]
That's weird. On my machine I can plot the data:

![immagine](https://user-images.githubusercontent.com/2884884/60519567-188ed080-9ce4-11e9-81e9-98f28c432ca9.png)

**Comment by cordrey** [comment]
Thanks,

I have since tried on a different macbook pro and I tried uninstalling and reinstalling the python with different versions and uninstalling and reinstalling the plugin and still the same error.  

Do have any suggestions on how I can debug the error?  I really love the plugin and really want it to work on my mac as I hate having to use my windows workstation to do all my processing.

**Comment by ghtmtt** [comment]
Could you please open the python console in QGIS and copy/paste these 2 lines:

```
import plotly
plotly.__version__
```

what is the output? Just copy/paste the text. Maybe you have some troubles with the plotly installation

**Comment by cordrey** [comment]
Sure:
plotly.__version__
'3.9.0'

**Comment by ghtmtt** [comment]
It seems that the error is due to the `re` module (regular expression) that cannot find a div in the html and replace the text with a default value.

Could you do the same of above for the `re` module?

```
import re
re.__version__
```

**Comment by cordrey** [comment]
re.__version__
'2.2.1'

thanks for looking into this!

**Comment by timlinux** [comment]
Confirm I get the same issue on mac here:

```
2019-07-12T10:46:39     WARNING    Traceback (most recent call last):
              File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/DataPlotly/data_plotly_dialog.py", line 1032, in createPlot
              self.plot_path = self.plotobject.buildFigure()
              File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/DataPlotly/data_plotly_plot.py", line 668, in buildFigure
              substr = match.group(1)
             AttributeError: 'NoneType' object has no attribute 'group'
             
```

**Comment by ghtmtt** [comment]
OK then it really seems a problem only related to (some) OSX version. 

Let's try to make a remote debugging:

* open the plugin folder (within the profile folder, then `python/plugins/Dataplotly`
* open the `data_plotly_plot.py` file
* search for `substr = match.group(1)`: you should find 3 occurrences
* before this line add `print(match)`, like:

```
        match = re.search(r'Plotly.newPlot\("([^"]+)', self.raw_plot)
        print(match)
        substr = match.group(1)

```
* close and restart QGIS
* open the python console
* try to use DataPlotly: the print output should appear in the python console, just paste the output here

**Comment by cordrey** [comment]
Output from print(match):
None

I dug a bit more using print outputs to debug and compared results to my working windows install.  It looks like on the OSX, the regex match is failing due to single quotes around the div id vs double quotes on windows. My regex is rusty, though, so was unable to test this until I have more time.  

Let me know what outputs you would like if any.

**Comment by ghtmtt** [comment]
As @nyalldawson referenced, commit bbff84e fixes the problem. We are in a deep refactoring moment, could you please try on your local computer to change the lines described in https://github.com/ghtmtt/DataPlotly/issues/123#issuecomment-512175144 with:

`match = re.search(r'Plotly.newPlot\(\s*[\'"](.+?)[\'"]', self.raw_plot)`

?

**Comment by cordrey** [comment]
replacement regex works well. Thanks for help!
