### ISSUE TITLE
Title settings have no effect

### ISSUE THREAD

**Issue by nyalldawson** [ghtmtt/DataPlotly#138]
@ghtmtt I'm stumped on this one. The layout title is correct when the call to  graph_objs.Layout happens in plot_type.py, but it's never shown on the actual plot surface. Do you have any clues?

**Comment by ghtmtt** [comment]
that's weird. Also the axis labels are not update. Will have a look

**Comment by ghtmtt** [comment]
I think it was an upstream problem of plotly. Fixed with be5ecc6827525e53b4af2735f1abb0999c6fe25f
