### ISSUE TITLE
Add the ability to redraw the graph using only features concerned by the Atlas coverage

### ISSUE THREAD

**Issue by haubourg** [ghtmtt/DataPlotly#140]
Next step, make the graph dynamically linked with atlas and report uses cases!

As for the UI, I imagine a checkbox to filter features concerned by the atlas geometry, or alternatively by the map extent,  in the plot parameter setup

**Comment by ghtmtt** [comment]
That's exactly the final aim of all! For some additional detail see https://north-road.com/qgis-data-plotly-campaign/

**Comment by nyalldawson** [comment]
Implemented in master
