### ISSUE TITLE
Help not load

### ISSUE THREAD

**Issue by Korto19** [ghtmtt/DataPlotly#141]
this is the message

Error opening C:/Users/xxxx/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/help/build/html/en/pie.html: The specified path could not be found

Failed to load URL file:///C:/Users/xxxx/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/help/build/html/en/pie.html.

Version of Qgis in use 3.8.3-Zanzibar and 3.9.0-Master

Best Regards

**Comment by ghtmtt** [comment]
fixed by https://github.com/ghtmtt/DataPlotly/pull/159. Now the docs are hosted on readthedoc: https://dataplotly-docs.readthedocs.io/en/latest/
