### ISSUE TITLE
Atlas Stacked bar plot 

### ISSUE THREAD

**Issue by cesarcorreo** [ghtmtt/DataPlotly#160]
I'm trying to do some Bar Plot graphs (or pie chart) linked to an atlas showing  the different % of area occupied by some building classes. (image 1) The attribute table with the data is located in image 2.
The "workflow" followed is:

1. Creation of the atlas
2. Selection of the layer and linked map
3. Selection of the x field and y field
4. Update diagram
5. New "y" field (with the next column of the layer) and new color for the y field.

**Result:**
The graph is updated according to the atlas and it works properly but it only shows 1 value of the column (image 1) and should be like image 5.

(I tried to do it with bar plot and pie chart but not successful). I'm doing something wrong or it's a bug?

Thanks 

Image 1:
![image](https://user-images.githubusercontent.com/25932761/67952180-2d756500-fbed-11e9-9c24-0cc09b4e52c8.png)

Image 2:
![image](https://user-images.githubusercontent.com/25932761/67952425-93fa8300-fbed-11e9-98a8-73c15b5d9979.png)

Image3:
![image](https://user-images.githubusercontent.com/25932761/67956814-f99e3d80-fbf4-11e9-90d3-21805bad8a7e.png)

Image 4:
![image](https://user-images.githubusercontent.com/25932761/67956923-1f2b4700-fbf5-11e9-9439-98addb0283d7.png)

Image 5.
![image](https://user-images.githubusercontent.com/25932761/67957559-171fd700-fbf6-11e9-9d09-c4c9775dea38.png)

**Comment by ghtmtt** [comment]
could you share a piece of your dataset? I think you are trying to do something that bar charts are not designed for

**Comment by ghtmtt** [comment]
Multiple layers in the same plot canvas are not supported yet in the print layout. A future enhancement. Thanks for the detailed description
