### ISSUE TITLE
Crash when removing and re-adding layer

### ISSUE THREAD

**Issue by jdugge** [ghtmtt/DataPlotly#163]
When the Assistant dialog for data defined marker colour is open, removing and re-adding the referenced layer crashes QGIS.

See attached GIF:
![2019-11-05_19-20-51](https://user-images.githubusercontent.com/2399255/68234593-d82cbf80-0001-11ea-91e5-f0e3f057efe8.gif)

**Comment by nyalldawson** [comment]
This bug is an upstream QGIS issue -- I've submitted a fix for it in QGIS.
