### ISSUE TITLE
Marker color cannot be set using value from field

### ISSUE THREAD

**Issue by jdugge** [ghtmtt/DataPlotly#165]
It is not possible to use a numerical field and a color scale from the dropdown to define the marker color. The marker color is instead set to a default value(`"#8ebad9"`), and the color scale in the plot stays empty.

See the attached GIF:

![2019-11-05_19-42-08](https://user-images.githubusercontent.com/2399255/68236056-b41ead80-0004-11ea-8759-5631dc28f21e.gif)

**Comment by ghtmtt** [comment]
Confirm the issue. We will have a look at this ASAP. Thanks for reporting.

**Comment by nyalldawson** [comment]
@ghtmtt 

I think for this one we'll need to separate the data-defined color handling into two separate choices.

1. Use native QGIS color ramps. This would allow use of things like the color ramp assistant and reuse of existing QGIS color ramps (of any format). Trade off is that we'd lose the ability to insert the color ramp legend into the plot.

or 

2. Use native plotly color ramps. This would allow use of the color ramp legend, but with the loss of the data defined color assistant option and only a choice of the included plotly color ramps. 

Both approaches have strong points for and against, so I think we need to consider letting users choose which method they want. What do you think?

**Comment by ghtmtt** [comment]
fixed in the newest version using the custom function. See https://twitter.com/hansakwast/status/1561795570880102402
