### ISSUE TITLE
changing color for pie chart

### ISSUE THREAD

**Issue by Geomini7** [ghtmtt/DataPlotly#167]
It seems that it's actually impossible to change color of generated pie charts. Unless I missed the option, is it possible to add the functionality ?

**Comment by ghtmtt** [comment]
it is possible but not implemented (yet). Actually it is not so straightforward because plotly accepts a list of colors that should be of the same length of the categories. See https://plot.ly/python/pie-charts/

**Comment by joaovitordeon** [comment]
fig.update_traces(textposition='inside', textinfo='value+percent', marker=dict(colors=['#FBE5DE', '#592671']))

**Comment by ghtmtt** [comment]
@joaovitordeon that's related more to ploty than dataplotly ;)
