### ISSUE TITLE
Data-defined property overrides do not work in layout

### ISSUE THREAD

**Issue by SGroe** [ghtmtt/DataPlotly#173]
The data-defined color/size/width overrides do not work when used in a layout. They work as expected in a normal chart (outside of layout designer). The feature subset filter works in both.

Replacing in the plot factory (e.g. for color)

```
default_value = QColor(self.settings.properties['in_color'])
value, _ = self.settings.data_defined_properties.valueAsColor(PlotSettings.PROPERTY_COLOR, context, default_value)
colors.append(value.name())
```

with

```
expression = self.settings.data_defined_properties.property(PlotSettings.PROPERTY_COLOR).asExpression()
color_expression, color_needs_geom, color_attrs = add_source_field_or_expression(expression)
if color_expression:
	color = color_expression.evaluate(context)
	colors.append(color)
```

solves the issue locally.

But as we want to use 'settings.data_defined_properties.valueAsColor', I try to figure out why it doesn't work in layout designer.

@ghtmtt, @nyalldawson: Can you confirm the issue? Any ideas why this happens?

**Comment by nyalldawson** [comment]
It works ok for me. Can you provide a sample project?

**Comment by SGroe** [comment]
You can download a very simple sample project here: https://secure.salzburgresearch.at/dl/?t=a191fea08bac636559ce4f3020aa527a

**Comment by SGroe** [comment]
`
value, _ = self.settings.data_defined_properties.valueAsColor(PlotSettings.PROPERTY_COLOR, context, default_value)
`

The variable '_' returns false

**Comment by SGroe** [comment]
The download ticket expired. Here is a new one: https://secure.salzburgresearch.at/dl/?t=cd078a9872875950ed837e45c36a9cd5

**Comment by ghtmtt** [comment]
thanks @SGroe we will take a look at this ASAP!
