### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Francini1981** [ghtmtt/DataPlotly#181]
I am new to QGIS and now exploring Data Plotly Plugin. I faced difficulty when attempting to develop a scatter plot for the below table

SiteNo       H1      H2         H3       H4      H5       H6      H7...................... H24
3078          20       40          56        70       65      100     105
3095           30      45          66        82       90      105      120
4020           55      77          98        103      120    130      150

I need to plot the where SiteNo=3095 for all the values from H1 to H24.
Thank you

**Comment by ghtmtt** [comment]
You can filter your data in QGIS (right click on the dataset -> Filter) or filter them directly in Dataplotly.

**Comment by ghtmtt** [comment]
@Francini1981 is the issue solved?

**Comment by Francini1981** [comment]
Many thanks for getting back to me, unfortunately, I am unable to resolve it. Is there a recommended tutorial or guidelines available to understand Data Plotly Plugin

**Comment by ghtmtt** [comment]
You can filter the desired point (`SiteNo=3095`) and then create as many plot as you want by overlapping them.

**Comment by ghtmtt** [comment]
@Francini1981 can we close the issue?

**Comment by ghtmtt** [comment]
closing. reopen if necessary
