### ISSUE TITLE
Make fonts adjustable

### ISSUE THREAD

**Issue by jdugge** [ghtmtt/DataPlotly#189]
It would be great if the fonts for the plots could be adjusted. The simplest way to do this would be to expose the `layout.font` key in the DataPlotly GUI (https://plot.ly/javascript/reference/#layout-font). There are also more specific keys for adjusting the fonts of the axis titles, labels, hovertext etc. separately, but that level of adjustability might not be necessary for most users.

**Comment by ghtmtt** [comment]
@jdugge I think that #278 implemented all these needs :)
