### ISSUE TITLE
installation bug with versions 3.0

### ISSUE THREAD

**Issue by gege41** [ghtmtt/DataPlotly#198]
Hello,
versions 3.0 do not install on QGIS 3.4.5 or QGIS 3.10; qgis stops dead!

Desktop 
 - OS: Windows 7 or 10
 - QGIS release 3.4.5 or 3.10.2
 - DataPlotly release 3.0 or 3.3

Thanks
Cordialy

**Comment by ghtmtt** [comment]
Hi. We have released the last 3.3 release. Can you try with this new version?

**Comment by ghtmtt** [comment]
@gege41 can we close this issue or is still valid?

**Comment by gege41** [comment]
Hello,
I'm sorry for my late response.
you can close this problem.
it was a proxy problem that had to be configured not in QGIS but in windows
Thank you
cordially
