### ISSUE TITLE
scatterplot of time-data cross-connects

### ISSUE THREAD

**Issue by danpejobo** [ghtmtt/DataPlotly#202]
**Describe the bug**
a bug plotting time-plots. the "line cross connects" a few places and runs back to start.

**To Reproduce**
1. plot this data geopkg provided as a scatter plot
- [time-plot-bug.zip](https://github.com/ghtmtt/DataPlotly/files/4298541/time-plot-bug.zip)

2. use x-field:  format_date( "dato_tid",'yyyy-MM-dd hh:mm:ss')
3. use y-field: kotevann
4. check results in screenshot below

**Screenshots**
![image](https://user-images.githubusercontent.com/36916831/76085144-c0fede00-5fb1-11ea-8f3e-d79bca8f7f17.png)
![image](https://user-images.githubusercontent.com/36916831/76084632-96605580-5fb0-11ea-887a-92356c6a099e.png)

**Desktop (please complete the following information):**
 - OS: win10
 - QGIS release: 3.12.0
 - DataPlotly release: 3.3

**Additional context**
I wonder if it have something with feature id? When i delete the "fid" (in the screenshot below) it works
![image](https://user-images.githubusercontent.com/36916831/76088241-f60e2f00-5fb7-11ea-967f-69cfc0515fb2.png)

**Comment by ghtmtt** [comment]
seems more a plotly related issue. I've reproduces your issue also outside DataPlotly. Here the python snippet to use (I've used `plotly.express`):

```
import pandas as pd
import plotly.express as px

df = pd.read_csv('plotly.csv')
fig = px.line(df, "dato_tid", "kotevann")
fig.show()
```

and the result:

![immagine](https://user-images.githubusercontent.com/2884884/76406768-9aaeb900-638a-11ea-8391-4e3bde898f81.png)

I'd suggest to contact plotly community itself ([https://community.plot.ly/](https://community.plot.ly/)) and keep us posted.

**Comment by ghtmtt** [comment]
Wait! I was too quick and hit Enter. 

To solve the issue within QGIS itself, you can use the `Order By Expression` algorithm in Processing and sort the layer with the `dato_tid` field. 

![immagine](https://user-images.githubusercontent.com/2884884/76407253-5839ac00-638b-11ea-8e1a-c69dadfcca93.png)

Once you have sorted the layer you can use it smoothly:

![immagine](https://user-images.githubusercontent.com/2884884/76407205-435d1880-638b-11ea-886e-ead4e7ba863d.png)

**Comment by danpejobo** [comment]
@ghtmtt great! 

any ideas why it might cross-connect without this sorting?

**Comment by ghtmtt** [comment]
not really.. seems more an internal method of plotly that is reading the values with an id that could not be in the same order of the x value. 

If you want please refer to the plotly issue tracker and keep us posted. Maybe is a bug or maybe is a standard behavior.

**Comment by danpejobo** [comment]
@ghtmtt searching the plotly forums you pointed to reveals that plotly does not sort the x-axis automatically before plotting the dataframe. So it must be sorted first. Thanks!
