### ISSUE TITLE
[Atlas] unprinted and inconsistent graphics with coverage vector

### ISSUE THREAD

**Issue by pigreco** [ghtmtt/DataPlotly#207]
I created a simple project and an atlas.

I notice some problems:

1. randomly the graphs are not printed when exported to PDF;

![image](https://user-images.githubusercontent.com/7631137/76709172-d0420200-66fc-11ea-9d46-2f2eacb1b1aa.png)

2. the printed graphics do not respect the coverage vector;
 
![image](https://user-images.githubusercontent.com/7631137/76709180-e64fc280-66fc-11ea-82a9-23f54c797142.png)

Leafing through the atlas, I notice that the creation of the charts is rather slow.

I attach a PDF exported from the attached project.

---
## OSGeo4W64 Win 10 - QGIS 3.12 București
---

![image](https://user-images.githubusercontent.com/7631137/76709264-d684ae00-66fd-11ea-9595-500872ff7e2b.png)

data and project:
[test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4334968/test_dataplotly35.zip)

**Comment by ghtmtt** [comment]
@nyalldawson can it be a refreshing delay of `QWebBrowser`?

**Comment by pigreco** [comment]
To demonstrate that atlas works but not serial printing, I made this test:

1. same project and same atlas
2. I printed the single pages in PDF, one by one;

![image](https://user-images.githubusercontent.com/7631137/76751173-6dde1580-677f-11ea-9d9e-70d2afe3115f.png)

3. then I merged the PDFs with external software

the prints are perfect!

here is the PDF

https://github.com/pigreco/COVID-19_ITA/files/4337701/ilovepdf_merged.pdf

**Comment by Krotalo25** [comment]
[Atlas_Prueba_LAMT_Completo.pdf](https://github.com/ghtmtt/DataPlotly/files/4338499/Atlas_Prueba_LAMT_Completo.pdf)

Try Linux Ubuntu 19.10 with QGIS 3.12. Full atlas publication

**Comment by SGroe** [comment]
> 1. randomly the graphs are not printed when exported to PDF;

I also see this problem with empty pages.

Additionally, subsequent report pages within a Field Group Section contain the same content (instead of the content corresponding to the current feature).

Exporting new PDFs or PNGs sometimes succeeds and sometimes fails.

**Comment by ghtmtt** [comment]
@nyalldawson could it be something related to QGIS and not to DataPlotly itself?

**Comment by ivn951** [comment]
I ran many tests with the **macOS** version of **QGIS**. Behaviour is less problematic than Win or Linux. With the data set [test_dataplotly35](https://github.com/ghtmtt/DataPlotly/files/4334968/test_dataplotly35.zip) the results are error-free with both versions 3.10 and 3.12. But with another data set [COVID19_3857_noVL_ogrVRT](https://github.com/pigreco/COVID-19_ITA/blob/master/macOS_Project/COVID19_3857_noVL_ogrVRT.qgs) there is no reliability of the results in the printing phase of the Atlas.

**Comment by pigreco** [comment]
If a new fundraiser is needed, please tell us now so we organize!

**Comment by SGroe** [comment]
I also think that this is a QGIS issue

**Comment by pigreco** [comment]
> I also think that this is a QGIS issue

Probably, we look forward to @nyalldawson  reply

**Comment by pigreco** [comment]
https://github.com/qgis/QGIS/issues/35173#issuecomment-601772810

**Comment by nyalldawson** [comment]
Hmm... I can't reproduce this locally....

**Comment by ghtmtt** [comment]
@pigreco could you please provide some more detailed information in order to be able to reproduce the issue also locally?

**Comment by pigreco** [comment]
what does it mean to reproduce it locally ??

**Comment by pigreco** [comment]
@nyalldawson @ghtmtt 

so you confirm that you used my attached project and that the graphs and table represent the same data ??

to reproduce it:
1. import a polygonal shapefile;
2. to import a CSV
3. create 1: m relationships between shp and csv
4. create atlas and use the shp as the cover vector;
5. add a map in the layout
6. add the related table in the layout with between attributes
7. add charts to the layout using attributes
8. print atlas
9. the graphs and table do not indicate the same thing.

shortly I will make a demonstration video

[test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4442733/test_dataplotly35.zip)

**Comment by nyalldawson** [comment]
Yes, on my machine (fedora 31) both linked projects export without issue.

**Comment by pigreco** [comment]
Thank you for your time, @nyalldawson 

> Yes, on my machine (fedora 31) both linked projects export without issue.

Please, can you attach the output PDF
thanks

Could it depend on PC resources ??
(mine is a 2015 Lenovo AMD - 8GB RAM
AMD FX-7500 Radeon R7 processor, 10 Compute Cores 4C + 6G, 2100 Mhz, 4 cores, 4 logical processors)

**Comment by ludovico85** [comment]
I agree with @pigreco. I have made two tests with two different machines, both with Windows10:

PC Desktop with i7-7700 @3.60 GHz and 16 GB of RAM - GeForce GTX 1050Ti (no issue)
Notebook with i5-3210M @2.50 GHz and 8 GB of RAM - AMD Radeon HD 7600M (issue)

[atlas_3.12.1.pdf](https://github.com/ghtmtt/DataPlotly/files/4443851/atlas_3.12.1.pdf)
[Uploading atlas_3.12.1_notebook.pdf…]()

**Comment by pigreco** [comment]
@nyalldawson 

An example of the mistake
The printed pages are equal two by two

![image](https://user-images.githubusercontent.com/7631137/78665670-7933e500-78d6-11ea-870d-0a013bdb8323.png)

**Comment by ghtmtt** [comment]
Something weird is happening. 

This is the layout generated with the atlas in the layout composer (e.g. 3: Lombardia) and the central plot is correctly generated:
![immagine](https://user-images.githubusercontent.com/2884884/78689449-a42e3100-78f6-11ea-9b0b-5c1c7474e650.png)
And this is the pdf exported:
![immagine](https://user-images.githubusercontent.com/2884884/78689555-bf993c00-78f6-11ea-831c-d58d71fddfb0.png)

The central plot is actually the same of the previous feature (2: Valle d'Aosta).

With some tests (kudos to all the people here) it seems that if you have a powerful machine (16 GB RAM, etc) it works fine, on older machines the process seems to stuck somewhere in the middle. That's super odd..

**Comment by alpterlab** [comment]
Same issue is happening when export as image file, even on low res (72dpi) .... 
Graph n. 2 is the same in both output.
![output_1 2](https://user-images.githubusercontent.com/20671397/78724259-5e408f80-792d-11ea-925f-931a886231fc.jpg)

**Comment by pigreco** [comment]
I add other tests (suggested by @matteo)

test | outcome | attached
----- | ----- | ----
a single graph | same problem | [1]
layout with three pages and one graph per page | same problem | [2]

[1] [ATLAS_SINGLE.pdf](https://github.com/ghtmtt/DataPlotly/files/4449179/ATLAS_SINGLE.pdf) (the graphs are equal two by two:  page 1 and 2, 3 and 4, 5 and 6 ....)

[2] [atlas_tre_pagine.pdf](https://github.com/ghtmtt/DataPlotly/files/4449175/atlas_tre_pagine.pdf) (like above)

**Comment by ghtmtt** [comment]
@nyalldawson I've created a more complex atlas with9 plots and A3 layout. From some test people made it seems that it really depends on the machine performance. I'm attaching a zip with the exact same project but with a new layout `atlas_complex`. [test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4460302/test_dataplotly35.zip)

**Comment by pigreco** [comment]
> @nyalldawson Ho creato un atlante più complesso con 9 grafici e layout A3. Da alcuni test le persone hanno fatto sembrare che dipenda davvero dalle prestazioni della macchina. Ti allego una zip con lo stesso identico progetto ma con un nuovo layout `atlas_complex`. [test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4460302/test_dataplotly35.zip)

@ghtmtt 

in this new project have you encountered errors ??
if yes, which ones ??
can you attach output PDF ??

i downloaded your project and i have this error
![image](https://user-images.githubusercontent.com/7631137/78976200-fd27e000-7b15-11ea-9114-12a8a997f01d.png)
---

Si è verificato un errore durante l'esecuzione del codice Python: 

ValueError: Invalid property specified for object of type plotly.graph_objs.Violin: 'box_visible'     Valid properties:         bandwidth             Sets the bandwidth used to compute the kernel density             estimate. By default, the bandwidth is determined by             Silverman's rule of thumb.         box             plotly.graph_objs.violin.Box instance or dict with             compatible properties         customdata             Assigns extra data each datum. This may be useful when             listening to hover, click and selection events. Note             that, "scatter" traces also appends customdata items in             the markers DOM elements         customdatasrc             Sets the source reference on plot.ly for  customdata .         fillcolor             Sets the fill color. Defaults to a half-transparent             variant of the line color, marker color, or marker line             color, whichever is available.         hoverinfo             Determines which trace information appear on hover. If             `none` or `skip` are set, no information is displayed             upon hovering. But, if `none` is set, click and hover             events are still fired.         hoverinfosrc             Sets the source reference on plot.ly for  hoverinfo .         hoverlabel             plotly.graph_objs.violin.Hoverlabel instance or dict             with compatible properties         hoveron             Do the hover effects highlight individual violins or             sample points or the kernel density estimate or any             combination of them?         ids             Assigns id labels to each datum. These ids for object             constancy of data points during animation. Should be an             array of strings, not numbers or any other type.         idssrc             Sets the source reference on plot.ly for  ids .         jitter             Sets the amount of jitter in the sample points drawn.             If 0, the sample points align along the distribution             axis. If 1, the sample points are drawn in a random             jitter of width equal to the width of the violins.         legendgroup             Sets the legend group for this trace. Traces part of             the same legend group hide/show at the same time when             toggling legend items.         line             plotly.graph_objs.violin.Line instance or dict with             compatible properties         marker             plotly.graph_objs.violin.Marker instance or dict with             compatible properties         meanline             plotly.graph_objs.violin.Meanline instance or dict with             compatible properties         name             Sets the trace name. The trace name appear as the             legend item and on hover. For box traces, the name will             also be used for the position coordinate, if `x` and             `x0` (`y` and `y0` if horizontal) are missing and the             position axis is categorical         opacity             Sets the opacity of the trace.         orientation             Sets the orientation of the violin(s). If "v" ("h"),             the distribution is visualized along the vertical             (horizontal).         pointpos             Sets the position of the sample points in relation to             the violins. If 0, the sample points are places over             the center of the violins. Positive (negative) values             correspond to positions to the right (left) for             vertical violins and above (below) for horizontal             violins.         points             If "outliers", only the sample points lying outside the             whiskers are shown If "suspectedoutliers", the outlier             points are shown and points either less than 4*Q1-3*Q3             or greater than 4*Q3-3*Q1 are highlighted (see             `outliercolor`) If "all", all sample points are shown             If False, only the violins are shown with no sample             points         scalegroup             If there are multiple violins that should be sized             according to to some metric (see `scalemode`), link             them by providing a non-empty group id here shared by             every trace in the same group.         scalemode             Sets the metric by which the width of each violin is             determined."width" means each violin has the same (max)             width*count* means the violins are scaled by the number             of sample points makingup each violin.         selected             plotly.graph_objs.violin.Selected instance or dict with             compatible properties         selectedpoints             Array containing integer indices of selected points.             Has an effect only for traces that support selections.             Note that an empty array means an empty selection where             the `unselected` are turned on for all points, whereas,             any other non-array values means no selection all where             the `selected` and `unselected` styles have no effect.         showlegend             Determines whether or not an item corresponding to this             trace is shown in the legend.         side             Determines on which side of the position value the             density function making up one half of a violin is             plotted. Useful when comparing two violin traces under             "overlay" mode, where one trace has `side` set to             "positive" and the other to "negative".         span             Sets the span in data space for which the density             function will be computed. Has an effect only when             `spanmode` is set to "manual".         spanmode             Sets the method by which the span in data space where             the density function will be computed. "soft" means the             span goes from the sample's minimum value minus two             bandwidths to the sample's maximum value plus two             bandwidths. "hard" means the span goes from the             sample's minimum to its maximum value. For custom span             settings, use mode "manual" and fill in the `span`             attribute.         stream             plotly.graph_objs.violin.Stream instance or dict with             compatible properties         text             Sets the text elements associated with each sample             value. If a single string, the same string appears over             all the data points. If an array of string, the items             are mapped in order to the this trace's (x,y)             coordinates. To be seen, trace `hoverinfo` must contain             a "text" flag.         textsrc             Sets the source reference on plot.ly for  text .         uid         unselected             plotly.graph_objs.violin.Unselected instance or dict             with compatible properties         visible             Determines whether or not this trace is visible. If             "legendonly", the trace is not drawn, but can appear as             a legend item (provided that the legend itself is             visible).         x             Sets the x sample data or coordinates. See overview for             more info.         x0             Sets the x coordinate of the box. See overview for more             info.         xaxis             Sets a reference between this trace's x coordinates and             a 2D cartesian x axis. If "x" (the default value), the             x coordinates refer to `layout.xaxis`. If "x2", the x             coordinates refer to `layout.xaxis2`, and so on.         xsrc             Sets the source reference on plot.ly for  x .         y             Sets the y sample data or coordinates. See overview for             more info.         y0             Sets the y coordinate of the box. See overview for more             info.         yaxis             Sets a reference between this trace's y coordinates and             a 2D cartesian y axis. If "y" (the default value), the             y coordinates refer to `layout.yaxis`. If "y2", the y             coordinates refer to `layout.yaxis2`, and so on.         ysrc             Sets the source reference on plot.ly for  y .         
Traceback (most recent call last):
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 129, in draw
    self.load_content()
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 162, in load_content
    self.web_page.mainFrame().setHtml(self.create_plot(), base_url)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 153, in create_plot
    factory = PlotFactory(self.plot_settings, self, polygon_filter=polygon_filter)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 113, in __init__
    self.rebuild()
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 398, in rebuild
    self.trace = self._build_trace()
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 415, in _build_trace
    return PlotFactory.PLOT_TYPES[self.settings.plot_type].create_trace(self.settings)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_types\violin.py", line 61, in create_trace
    box_visible=settings.properties['violin_box']
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\plotly\graph_objs\_violin.py", line 1723, in __init__
    self._process_kwargs(**dict(arg, **kwargs))
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\plotly\basedatatypes.py", line 2345, in _process_kwargs
    self._raise_on_invalid_property_error(*kwargs.keys())
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\plotly\basedatatypes.py", line 2939, in _raise_on_invalid_property_error
    prop_descriptions=self._prop_descriptions))
ValueError: Invalid property specified for object of type plotly.graph_objs.Violin: 'box_visible'

    Valid properties:
        bandwidth
            Sets the bandwidth used to compute the kernel density
            estimate. By default, the bandwidth is determined by
            Silverman's rule of thumb.
        box
            plotly.graph_objs.violin.Box instance or dict with
            compatible properties
        customdata
            Assigns extra data each datum. This may be useful when
            listening to hover, click and selection events. Note
            that, "scatter" traces also appends customdata items in
            the markers DOM elements
        customdatasrc
            Sets the source reference on plot.ly for  customdata .
        fillcolor
            Sets the fill color. Defaults to a half-transparent
            variant of the line color, marker color, or marker line
            color, whichever is available.
        hoverinfo
            Determines which trace information appear on hover. If
            `none` or `skip` are set, no information is displayed
            upon hovering. But, if `none` is set, click and hover
            events are still fired.
        hoverinfosrc
            Sets the source reference on plot.ly for  hoverinfo .
        hoverlabel
            plotly.graph_objs.violin.Hoverlabel instance or dict
            with compatible properties
        hoveron
            Do the hover effects highlight individual violins or
            sample points or the kernel density estimate or any
            combination of them?
        ids
            Assigns id labels to each datum. These ids for object
            constancy of data points during animation. Should be an
            array of strings, not numbers or any other type.
        idssrc
            Sets the source reference on plot.ly for  ids .
        jitter
            Sets the amount of jitter in the sample points drawn.
            If 0, the sample points align along the distribution
            axis. If 1, the sample points are drawn in a random
            jitter of width equal to the width of the violins.
        legendgroup
            Sets the legend group for this trace. Traces part of
            the same legend group hide/show at the same time when
            toggling legend items.
        line
            plotly.graph_objs.violin.Line instance or dict with
            compatible properties
        marker
            plotly.graph_objs.violin.Marker instance or dict with
            compatible properties
        meanline
            plotly.graph_objs.violin.Meanline instance or dict with
            compatible properties
        name
            Sets the trace name. The trace name appear as the
            legend item and on hover. For box traces, the name will
            also be used for the position coordinate, if `x` and
            `x0` (`y` and `y0` if horizontal) are missing and the
            position axis is categorical
        opacity
            Sets the opacity of the trace.
        orientation
            Sets the orientation of the violin(s). If "v" ("h"),
            the distribution is visualized along the vertical
            (horizontal).
        pointpos
            Sets the position of the sample points in relation to
            the violins. If 0, the sample points are places over
            the center of the violins. Positive (negative) values
            correspond to positions to the right (left) for
            vertical violins and above (below) for horizontal
            violins.
        points
            If "outliers", only the sample points lying outside the
            whiskers are shown If "suspectedoutliers", the outlier
            points are shown and points either less than 4*Q1-3*Q3
            or greater than 4*Q3-3*Q1 are highlighted (see
            `outliercolor`) If "all", all sample points are shown
            If False, only the violins are shown with no sample
            points
        scalegroup
            If there are multiple violins that should be sized
            according to to some metric (see `scalemode`), link
            them by providing a non-empty group id here shared by
            every trace in the same group.
        scalemode
            Sets the metric by which the width of each violin is
            determined."width" means each violin has the same (max)
            width*count* means the violins are scaled by the number
            of sample points makingup each violin.
        selected
            plotly.graph_objs.violin.Selected instance or dict with
            compatible properties
        selectedpoints
            Array containing integer indices of selected points.
            Has an effect only for traces that support selections.
            Note that an empty array means an empty selection where
            the `unselected` are turned on for all points, whereas,
            any other non-array values means no selection all where
            the `selected` and `unselected` styles have no effect.
        showlegend
            Determines whether or not an item corresponding to this
            trace is shown in the legend.
        side
            Determines on which side of the position value the
            density function making up one half of a violin is
            plotted. Useful when comparing two violin traces under
            "overlay" mode, where one trace has `side` set to
            "positive" and the other to "negative".
        span
            Sets the span in data space for which the density
            function will be computed. Has an effect only when
            `spanmode` is set to "manual".
        spanmode
            Sets the method by which the span in data space where
            the density function will be computed. "soft" means the
            span goes from the sample's minimum value minus two
            bandwidths to the sample's maximum value plus two
            bandwidths. "hard" means the span goes from the
            sample's minimum to its maximum value. For custom span
            settings, use mode "manual" and fill in the `span`
            attribute.
        stream
            plotly.graph_objs.violin.Stream instance or dict with
            compatible properties
        text
            Sets the text elements associated with each sample
            value. If a single string, the same string appears over
            all the data points. If an array of string, the items
            are mapped in order to the this trace's (x,y)
            coordinates. To be seen, trace `hoverinfo` must contain
            a "text" flag.
        textsrc
            Sets the source reference on plot.ly for  text .
        uid

        unselected
            plotly.graph_objs.violin.Unselected instance or dict
            with compatible properties
        visible
            Determines whether or not this trace is visible. If
            "legendonly", the trace is not drawn, but can appear as
            a legend item (provided that the legend itself is
            visible).
        x
            Sets the x sample data or coordinates. See overview for
            more info.
        x0
            Sets the x coordinate of the box. See overview for more
            info.
        xaxis
            Sets a reference between this trace's x coordinates and
            a 2D cartesian x axis. If "x" (the default value), the
            x coordinates refer to `layout.xaxis`. If "x2", the x
            coordinates refer to `layout.xaxis2`, and so on.
        xsrc
            Sets the source reference on plot.ly for  x .
        y
            Sets the y sample data or coordinates. See overview for
            more info.
        y0
            Sets the y coordinate of the box. See overview for more
            info.
        yaxis
            Sets a reference between this trace's y coordinates and
            a 2D cartesian y axis. If "y" (the default value), the
            y coordinates refer to `layout.yaxis`. If "y2", the y
            coordinates refer to `layout.yaxis2`, and so on.
        ysrc
            Sets the source reference on plot.ly for  y .
        


Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.12.1-București București, 121cc00ff0 

Percorso Python:
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos
C:/OSGEO4~1/apps/qgis/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/pigre/Downloads/test_dataplotly35

**Comment by ghtmtt** [comment]
@pigreco in which moment is the error popping up? When loading the project?

**Comment by pigreco** [comment]
@ghtmtt 

> @pigreco in which moment is the error popping up? When loading the project?

when active atlas

**Comment by ghtmtt** [comment]
weird, try with this updated project: [test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4460910/test_dataplotly35.zip)

and this the output: [atlas complex.pdf](https://github.com/ghtmtt/DataPlotly/files/4460935/atlas.complex.pdf) 

@pigreco could you have a look at it please?

**Comment by pigreco** [comment]
@ghtmtt 

I downloaded the new project, opened with QGIS 3.10.4 and activated atlas, everything ok, no errors.

here PDF output atlas complex
[atlas_complex.pdf](https://github.com/ghtmtt/DataPlotly/files/4461087/atlas_complex.pdf)

**Comment by nyalldawson** [comment]
@pigreco can you test the proposed fix from #216 ? I still can't reproduce locally, so need some feedback on whether that fix actually works!

**Comment by nyalldawson** [comment]
Ping @alpterlab , @SGroe , @ivn951  @Krotalo25 also -- are you able to test the proposed fix from #216?

**Comment by pigreco** [comment]
> @pigreco can you test the proposed fix from #216 ? I still can't reproduce locally, so need some feedback on whether that fix actually works!

@nyalldawson , @ghtmtt 

`in the meantime, thank you very much to you and Matteo.`

I did tests using the complex project of matteo and my simple one attached to this issue:

I always have the same problems.

In the atlas printed in PDF I put the characteristics of the PC and QGIS. (profile used is NEW)

- [complex project](https://github.com/ghtmtt/DataPlotly/files/4460910/test_dataplotly35.zip) → 
[atlas_complex_01.pdf](https://github.com/ghtmtt/DataPlotly/files/4485678/atlas_complex_01.pdf)

- [simple project](https://github.com/ghtmtt/DataPlotly/files/4443178/test_dataplotly35.zip) → 
[atlas_small.pdf](https://github.com/ghtmtt/DataPlotly/files/4485682/atlas_small.pdf)

**Comment by pigreco** [comment]
@nyalldawson  and @ghtmtt 

I have to correct my answer this morning,
the patch works both on new and old profile, only that it is necessary to restart QGIS otherwise it does not see the patch.

thank you very much, and W QGIS

FOR ME CLOSED PROBLEM.

**Comment by ghtmtt** [comment]
thanks to all for testing and @nyalldawson for fixing

**Comment by pigreco** [comment]
@ghtmtt @nyalldawson 
the problem reoccurs in 3.34.11
in addition to the excessive slowness in browsing atlases

**Comment by ghtmtt** [comment]
is the initial attached project still valid to reproduce the issue?

**Comment by pigreco** [comment]
> is the initial attached project still valid to reproduce the issue?

no.
As soon as I can, if necessary, I attach the project and data to reproduce it

**Comment by pigreco** [comment]
@ghtmtt 
Maybe it's better to open another issue?

**Comment by ghtmtt** [comment]
sounds good, thanks!

**Comment by pigreco** [comment]
Unusable! in production
![image](https://github.com/user-attachments/assets/9ba3e78e-2708-496d-bc81-503e787d7d34)

**Comment by ghtmtt** [comment]
can you please share a project so I can test it and try to understand where the bug is?

**Comment by pigreco** [comment]
> can you please share a project so I can test it and try to understand where the bug is?

Yes, but in private.
Because the data is private.
