### ISSUE TITLE
Processing model Python error

### ISSUE THREAD

**Issue by magnusnil** [ghtmtt/DataPlotly#209]
When I try adding DataPlotly in a processing model, I get an error:

Exception: unknown Traceback (most recent call last):
  File
"C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerDialog.py",
line 796, in addAlgorithm
    alg =
QgsApplication.processingRegistry().createAlgorithmById(algorithm.id())
Exception: unknown

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914
64 bit (AMD64)]
QGIS version: 3.4.11-Madeira Madeira, 9a8a6d4687

1. Create a new, empty processing model
2. Add DataPlotly
3. You get the Python error

I use:
- QGIS 3.4.11, 64 bit
- DataPlotly 3.5
- Windows 10, 64 bit

**Comment by ghtmtt** [comment]
related to #234. Closing this issue so we have a single place
