### ISSUE TITLE
QGIS crashes with Data Plotly loading!!

### ISSUE THREAD

**Issue by hoseinmadadi** [ghtmtt/DataPlotly#210]
There is an error when Data Plotly 3.5 is activated on windows 8 and qgis 3.12.1 crashes.

![image](https://user-images.githubusercontent.com/9200184/78122995-c28dbb80-7422-11ea-920d-1e157ad25ac1.png)

I reinstalled QGIS from exe file and also from OSGeo4W installer, but I could not fix it. Is it bug or not?

**Comment by nyalldawson** [comment]
I'm not even sure QGIS itself is fully supported on Windows 8...

**Comment by hoseinmadadi** [comment]
Hi @nyalldawson, I would like to use QGIS in linux and I have been used without error, but I am forced to use it in Win 8.1.

**Comment by hoseinmadadi** [comment]
This problem solved by:
https://github.com/GIS4WRF/gis4wrf/issues/103#issuecomment-575889035
change C:\Program Files\QGIS 3.12\apps\Qt5\bin\Qt5Bluetooth.dll to Qt5Bluetooth.dll1 !!!!!!!!
Not Qt5Bluetooth.dll == Not problem in Data Plotly use.

**Comment by VxTedxV** [comment]
Same issue, same config (Win 8.1 pro) BUT for me only occurs since the last update of Data Plotly (works fine under 3.6)

PS : [new releases in github](https://github.com/ghtmtt/DataPlotly/releases) don't seem to be published anymore, but are updated in QGIS plugins
