### ISSUE TITLE
Creating pie charts by feature using attribute data

### ISSUE THREAD

**Issue by hugonbgg** [ghtmtt/DataPlotly#211]
I have this dataset with districts in São Paulo that contains the total population, the black population and the white population.
I want to generate a pie chart by district showing the black and white population, but I can't do that using Data Plotly, I don't know if I'm the one who doesn't know how to create or if it's not possible.
Using the QGIS diagrams I can generate the graph, but I wanted to use the plugin because I want to use it in the atlas.

dataset sample:
![image](https://user-images.githubusercontent.com/11204577/78512337-0dd50080-777a-11ea-970c-e0603dae7855.png)

chart example:
![image](https://user-images.githubusercontent.com/11204577/78512347-20e7d080-777a-11ea-81d5-ee5cdc85cbcf.png)

**Comment by ghtmtt** [comment]
the table should be *reshaped*:


Distrito | Type | Total
-- | -- | --
A | Black | 898
A | White | 256
A | Black | 700
B | Black | 175
B | Black | 454
B | White | 135
B | White | 400
B | Black | 889
B | Black | 296
B | Black | 839
C | White | 965
C | Black | 651
C | Black | 212
D | White | 772
D | White | 473
E | White | 467
E | White | 937
E | White | 106

![immagine](https://user-images.githubusercontent.com/2884884/78528591-02b4bb80-77e0-11ea-939a-a8e73a5a4ad1.png)

**Comment by ghtmtt** [comment]
@hugonbgg is the issue solved with this suggestion? Can we close it?

**Comment by hugonbgg** [comment]
Thanks, @ghtmtt ! now it worked!

**Comment by verteux** [comment]
This approach will duplicate geographic objects and create overlap. It is a solution, but not the best.

**Comment by ghtmtt** [comment]
> This approach will duplicate geographic objects and create overlaps. It is a solution, but not the best.

true. However you can also use the `Aggregate` algorithm to group by and make a sum of the needed field. In other words, the original data set is not immediately suitable for that kind of plot.

**Comment by verteux** [comment]
Being able to pick more then one column to distribute data on a pie chart would be the best solution, by keeping the original data. You think that's feasible with plotly ?

**Comment by ghtmtt** [comment]
I don't think so. Pie charts are design to work in a particular way, see the official documentation: https://plotly.com/python/pie-charts/
