### ISSUE TITLE
Selected combobox value is reset after loading chart settings

### ISSUE THREAD

**Issue by SGroe** [ghtmtt/DataPlotly#213]
**Describe the bug**
In DataPlotlyPanelWidget, the method set_settings() correctly sets values to all combo boxes. Unfortunately, the selected values are reset to the default values, because the method refreshWidgets() is called afterwards. Here, all combo boxes are cleared and the items are added again.

I have implemented a fast solution like this:

```
selection = self.marker_type_combo.currentText()  # first new line
self.marker_type_combo.clear()
for k, v in self.marker_types.items():
    self.marker_type_combo.addItem(k, v)
self.marker_type_combo.setCurrentText(selection)  # second new line
```

I am not sure if this is the best way to solve the bug. Maybe the order of calling methods should be changed. However, I do not have time to take a look at this right now. Maybe, someone of you can do this.

**To Reproduce**
1. Create new layout and new chart
2. Change a combo box value (e.g. marker type, point type and line type for scatter plots)
3. Close plot properties
4. Open plot setup again
4. See the reset combo box values

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - QGIS release 3.12
 - DataPlotly release 3.5

**Additional context**

**Comment by ghtmtt** [comment]
mmm cannot reproduce if I understood it correctly:

* create a new chart in the layout composer and set it up
* go around in the layout composer
* when re-entering in the set up of the chart X and Y values are cleared and don't contain the values entered? 

Is this happening also after you amazing PR with multiple charts?

**Comment by SGroe** [comment]
The problem does not occur at QgsFieldExpressionWidgets (x and y values). It occurs at default combo boxes (e.g. marker type, point type and line type for scatter plots), where the items are re-added in DataPlotlyPanelWidget.refreshWidgets()

I have tested with the current version.
