### ISSUE TITLE
"This Windows version (6.3.9600) does not support the required bluetooth API."

### ISSUE THREAD

**Issue by monticola2** [ghtmtt/DataPlotly#217]
When trying to activate the DataPlotly Plugin an error notification window appears saying "This Windows version (6.3.9600) does not support the required bluetooth API. Consider updating to a more recent Windows (10.0.10685 or above)."
When I click ok, QGIS crashes. Upon restarting QGIS sais it has removed/deactivated the plugin because it has crashed.
I am not sure if this has actually to do with the plugin itself or with the QGIS installation I use. However I have only encountered this with the DataPlotly Plugin, everything else works fine. Maybe it is helpful for others that encounter the same issue.

I have found a similar/near identical issue filed here:
https://github.com/GIS4WRF/gis4wrf/issues/103

My current solution (as mentioned in the link above) is to rename the files "QtBluetooth.pyd" and "QtBluetooth.pyi" to "QtBluetooth1.pyd" and "QtBluetooth1.pyi" in the folder "C:\Program Files\QGIS 3.10\apps\Python37\lib\site-packages\PyQt5". It solves the problem but I don't think it is perfect.

I have encountered this issue with the following setup:
Windows 8.1 Pro
QGIS versions 3.10.4, 3.10.5, 3.12.1 and 3.12.2 (standalone installers)
Data Plotly 3.6

**Comment by ghtmtt** [comment]
I really think this is a Windows8-QGIS related behavior and not a DataPlotly bug. https://github.com/ghtmtt/DataPlotly/issues/210#issuecomment-607155215

**Comment by ghtmtt** [comment]
Closing this for now. Reopen if necessary.

**Comment by VxTedxV** [comment]
What about this ?
https://github.com/qgis/QGIS/issues/28686#issuecomment-495901222

**Comment by ghtmtt** [comment]
That's really strange because it happens just with old version of Windows and not for every user.
