### ISSUE TITLE
Errors during QGIS 3.12.2 install with apt on Ubuntu 20.04

### ISSUE THREAD

**Issue by monetschemist** [ghtmtt/DataPlotly#221]
Yesterday I upgraded my Ubuntu 19.10 desktop to 20.04.  During that, my QGIS repository was turned off and when I re-enabled it and redid the install of 3.12.2 I noticed the following error messages during the install:
`Setting up python3-plotly (4.4.1+dfsg-1) ...
/usr/lib/python3/dist-packages/_plotly_utils/utils.py:214: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (iso_string.split("-")[:3] is "00:00") or (iso_string.split("+")[0] is "00:00"):
/usr/lib/python3/dist-packages/_plotly_utils/utils.py:214: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (iso_string.split("-")[:3] is "00:00") or (iso_string.split("+")[0] is "00:00"):
/usr/lib/python3/dist-packages/plotly/figure_factory/_candlestick.py:194: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if direction is "increasing":
/usr/lib/python3/dist-packages/plotly/figure_factory/_candlestick.py:199: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif direction is "decreasing":
/usr/lib/python3/dist-packages/plotly/figure_factory/_ohlc.py:176: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if direction is "increasing":
/usr/lib/python3/dist-packages/plotly/figure_factory/_ohlc.py:179: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif direction is "decreasing":
/usr/lib/python3/dist-packages/plotly/matplotlylib/renderer.py:460: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if props["offset_coordinates"] is "data":
/usr/lib/python3/dist-packages/plotly/matplotlylib/renderer.py:572: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if props["coordinates"] is not "data":`

To be clear I haven't tried using the software; these were emitted during the "apt install" step.

**Comment by nyalldawson** [comment]
That error is from the python plotly package, it's not coming from this plugin.

You'll need to file this issue with the Ubuntu plotly package instead

**Comment by monetschemist** [comment]
Thank you!

**Comment by monetschemist** [comment]
In case it helps anyone here that's reported here now:

https://bugs.launchpad.net/ubuntu/+source/plotly/+bug/1875992

**Comment by nyalldawson** [comment]
@monetschemist perfect! FYI it looks like this issue is more widespread then just the plotly package. Someone just reported the same error being raised from the python grass package on 20.04...

**Comment by monetschemist** [comment]
Thanks, that was me as well, happened at the same moment.  That bug is also filed on launchpad.

**Comment by monetschemist** [comment]
The Debian folks are on their game, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952489
