### ISSUE TITLE
How change size and labels colour ?

### ISSUE THREAD

**Issue by ambarja** [ghtmtt/DataPlotly#232]
Recently, I was creating report in **QGIS** using atlas with the new version of **DataPlotly**, the new version is **really amazing** because the colour of de bar is the same of my classified map, however I'm trying to **change size and labels color ** of the bar,but I think is not available.
Could you help me ? 
Thanks!
![](https://github.com/barja8/Friends/blob/master/QGIS/Img/Atlas/numero02.gif?raw=true)

**Comment by ghtmtt** [comment]
Sorry for the late reply. You get it, it not **yet** implemented but definitely possible. Hopefully we will have time to dive into all these customization.

BTW: amazing report ;)

**Comment by ghtmtt** [comment]
@ambarja customization of the labels both font, size and color is now available. Closing this ticket. Thanks for reporting!
