### ISSUE TITLE
Use symbol_color variable for legend

### ISSUE THREAD

**Issue by jvdkwast** [ghtmtt/DataPlotly#233]
Nyall Dawson showed in his demo on YouTube today that you can use the styling colours of a layer for label font colours by using @symbol_color as a variable. I wonder if it would be possible to implement that for the colours of DataPlotly legends.

It's mentioned [here](https://youtu.be/h-mpUkwDdOQ?t=3007) in the video (50m07s)

**Comment by nyalldawson** [comment]
Can you give some more example of how this would be used? I'm struggling to understand the use case

**Comment by jvdkwast** [comment]
Here's a video about the use case: [https://youtu.be/QbKmJ7Dg3o0](https://youtu.be/QbKmJ7Dg3o0)

**Comment by chrisgraf** [comment]
@nyalldawson : The usecase would be the synchronization of the symbology color and the associated color in the diagram.

**Comment by katagen** [comment]
This feature will be very useful!

**Comment by ghtmtt** [comment]
done in https://github.com/ghtmtt/DataPlotly/pull/288
