### ISSUE TITLE
[Processing] Build a generic plot

### ISSUE THREAD

**Issue by jonnyforestGIS** [ghtmtt/DataPlotly#234]
Hi @ghtmtt,
when I try to do Build a generic plot using processing toolbox I have this Python error:

```python

2020-08-07T13:33:49     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 236, in executeAlgorithm
              alg = self.algorithmTree.selectedAlgorithm().create() if self.algorithmTree.selectedAlgorithm() is not None else None
             _core.QgsProcessingException: Error creating algorithm from createInstance()

```

Tested on a new profile only with plotly plugin install.

QGIS version | 3.10.6-A Coruña | QGIS code revision | ec80021f49
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 7 SP 1 (6.1)
Active python plugins | DataPlotly; db_manager; MetaSearch; processing

Plotly QGIS python version: 3.3.0

Cheers.

**Comment by ghtmtt** [comment]
Hi @jonnyforestGIS. Working on it, thanks for the ticket. Can be merged with #92

**Comment by jonnyforestGIS** [comment]
Thanks @ghtmtt , let me know if you need help on the test.

**Comment by agiudiceandrea** [comment]
@ghtmtt it seems to me this bug still occurs, doesn't it?

```
2022-05-12T12:59:19     WARNING    NotImplementedError: QgsProcessingAlgorithm.createInstance() is abstract and must be overridden
             
2022-05-12T12:59:20     WARNING    Traceback (most recent call last):
              File "F:/QGIS/OSGEO4~1.5/qgis/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 239, in executeAlgorithm
              alg = self.algorithmTree.selectedAlgorithm().create(config) if self.algorithmTree.selectedAlgorithm() is not None else None
             _core.QgsProcessingException: Error creating algorithm from createInstance()
```

**Comment by ghtmtt** [comment]
yes it is still there. I froze it because I'm thinking to make some refactoring. will see if I can make a quick push on it

**Comment by ghtmtt** [comment]
that's the new approach I was thinking: https://github.com/ghtmtt/DataPlotly/pull/300
