### ISSUE TITLE
Make the plugin compatible for QGIS Server

### ISSUE THREAD

**Issue by Gustry** [ghtmtt/DataPlotly#239]
**Describe the solution you'd like**

As it's possible to have QGIS Layouts with Dataplotly component, it would be nice to have Dataplotly compatible for QGIS Server.

So we can print layouts (with or without atlas) from QGIS Server with a `GetPrint` request.
I'm not sure what is happening right now if you give a layout with a plotly componenent inside.

It's just an idea for now ;-)

**Comment by Gustry** [comment]
Mostly done in #266 

I still would like to check one thing : 

* [ ] Security if the layer is filtered, or user permissions

**Comment by ghtmtt** [comment]
@Gustry I'm closing this ticket (since you have done it :) ) and eventually open other more *atomic* ones
