### ISSUE TITLE
Only selected features

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#24]
Allow to take into account only the selected features with a checkbox

**Comment by ghtmtt** [comment]
fixed in dd37944

**Comment by leonmvd** [comment]
This option is not always available

**Comment by ghtmtt** [comment]
what do you mean here? If the layer don't have any selected feature the checkbox is deactivated.

**Comment by mazzma12** [comment]
@ghtmtt  I think he mean this case : when you select features of your layers using the selector by drawing a rectangle 

![image](https://user-images.githubusercontent.com/23187108/46547939-d90a9380-c8cd-11e8-82f1-ac20a085d882.png)

**Comment by ghtmtt** [comment]
I think this is a duplicate of #42 

BTW: if you have a selection, in order to activate the checkbox in DataPlotly you need to change the layer and then re change to the layer with the selected features. Then it should work.

But still a bug to fix

**Comment by mazzma12** [comment]
Thanks for the trick. Indeed after duplicating my layer and doing a switch I had the possibility to tick the box
