### ISSUE TITLE
Accessing the APIs of Dataplotly from Python

### ISSUE THREAD

**Issue by kvsandy** [ghtmtt/DataPlotly#240]
Hi, 

I have started using the Dataplotly tool and it has been amazing. I'm working on my plugin and started using Dataplotly for data visualization. Since I wanted to automate the graph creation, I started looking for APIs and found out that Dataplotly has APIs in the BETA version. I tried accessing it from version 3.7.1, but the loadPlot() wasn't working. Can you please let me know on how I can access the BETA version?

**Comment by ghtmtt** [comment]
the API has not been exposed after the crowdfunding campaign and the code refactoring. Can I ask you to pen a feature request? We are starting to have some really nice feature to work on ;)

**Comment by kvsandy** [comment]
Thank you, will open a feature request.

**Comment by ghtmtt** [comment]
duplicate of #241. Thanks @kvsandy we will do what we can :)
