### ISSUE TITLE
Can't reverse colour schema

### ISSUE THREAD

**Issue by iboates** [ghtmtt/DataPlotly#242]
Not sure if I am just not doing this right, but using `array_reverse()` in the marker colour definition doesn't seem to work. I want to reverse the direction of the colour gradient.

Example:

```
array_foreach(
        generate_series(0, 24445),
        ramp_color( 'RdYlGn', @element/50)
)
```

produces:

![image](https://user-images.githubusercontent.com/13814358/99563416-861aca00-29c9-11eb-9390-66f5ef80c957.png)

But this:

```
array_reverse(array_foreach(
        generate_series(0, 24445),
        ramp_color( 'RdYlGn', @element/50)
))
```

produces:

![image](https://user-images.githubusercontent.com/13814358/99563526-a34f9880-29c9-11eb-9418-24005cc6462a.png)

Is there another way to flip the colour ramp?

If it helps, the reason I am trying to do this is actually to force the midpoint of the colour ramp to be at a specific value, by merging two colour ramps together like so:

```
string_to_array(

concat(

array_to_string(
array_reverse(
    array_foreach(
        generate_series(0, 12223 ),
        ramp_color( 'YlGn', @element/25)
    )
),
	delimiter:=';'
)
,
';'
,
array_to_string(
    array_foreach(
        generate_series(12223 , 24445),
        ramp_color( 'YlOrRd', @element/25)
    ),
	delimiter:=';'
)

),
delimiter:=';'

)
```

But this doesn't work at all and just produces a fully green graph. Can you advise on how to do this? I want to make it so the medium of the data will have to switch from the red->yellow to the yellow->green colour ramp.

**Comment by ghtmtt** [comment]
is this issue still valid?
