### ISSUE TITLE
user.groups.add(group) AttributeError: 'NoneType' object has no attribute 'groups' error comes

### ISSUE THREAD

**Issue by Meenukutty1996** [ghtmtt/DataPlotly#243]
forms.py

class CreateUserForm(forms.Form):
        first_name = forms.CharField(label='Firstname')
        last_name = forms.CharField(label='Lastname',required=False)
        mobile = forms.CharField(label='Mobile')
        email = forms.EmailField(label='Email',required=False)
        address1 =forms.CharField(label='Address Line 1',widget=forms.Textarea(attrs={"rows":2, "cols":20}))
        address2 =forms.CharField(label='Address Line 2',widget=forms.Textarea(attrs={"rows":2, "cols":20}),required=False)
        image = forms.ImageField(max_length=200,required=False)
        username = forms.CharField(label='Username')
        password = forms.CharField(widget=forms.PasswordInput)

views.py 

def register(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        
        if form.is_valid():
            ui = User()
            ui.username = request.POST.get('username')
            ui.password = request.POST.get('password')
            ui.first_name = request.POST.get('first_name')
            ui.last_name = request.POST.get('last_name')
            ui.email = request.POST.get('email')
            # user = User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)
            user = ui.save()
            obj = User.objects.latest('id')
            cli = Client_profile_master()
            cli.first_name = request.POST.get('first_name')
            cli.last_name = request.POST.get('last_name')
            cli.email = request.POST.get('email')
            cli.mobile_no = request.POST.get('mobile')
            cli.address_1 = request.POST.get('address1')
            cli.address_2 = request.POST.get('address2')
            cli.image=request.FILES.get('image')
            cli.user=obj
            # emp.save()
            # client = Client_profile_master.objects.create(first_name=first_name,last_name=last_name,email=email,mobile=mobile,address1=address1,address2=address2,image=image,user=obj)
            cli.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='Client')
            user.groups.add(group)

            messages.success(
                request, f'Account created successfully for {username} !!!')
            return redirect('login')
        else:
            return redirect('/')
    else:
        form = CreateUserForm()
    return render(request, 'sites/register.html', {'form': form})

**Comment by ghtmtt** [comment]
are you sure that this report is for DataPlotly?

**Comment by AndreasRabe** [comment]
I get a similar error message when creating any kind of plot after clicking on "Create Plot" :

![image](https://user-images.githubusercontent.com/45030715/111217891-5de95380-85d6-11eb-997e-2b9e2b47b2ea.png)


```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'group' 
Traceback (most recent call last):
  File "C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly_dialog.py", line 1029, in createPlot
    self.plot_path = self.plotobject.buildFigures(self.ptype, pl)
  File "C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly_plot.py", line 730, in buildFigures
    substr = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.0-Hannover Hannover, 43b64b13f3 

Python Path:
C:/QGIS/apps/qgis/./python
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\source\QGISPlugIns
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/QGIS/apps/qgis/./python/plugins
C:\QGIS\apps\Python37
C:\QGIS\apps\Python37\Scripts
C:\QGIS\bin\python37.zip
C:\QGIS\apps\Python37\DLLs
C:\QGIS\apps\Python37\lib
C:\QGIS\bin
C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages
C:\QGIS\apps\Python37\lib\site-packages
C:\QGIS\apps\Python37\lib\site-packages\win32
C:\QGIS\apps\Python37\lib\site-packages\win32\lib
C:\QGIS\apps\Python37\lib\site-packages\Pythonwin
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BitFlagRenderer
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BitFlagRenderer\bitflagrenderer
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\site-packages
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\externals\qps\externals
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\site-packages
C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vrtbuilderplugin
C:\Users\janzandr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vrtbuilderplugin\vrtbuilder
C:/Work
```

**Comment by ghtmtt** [comment]
@AndreasRabe can you share the dataset? Or a piece of it

**Comment by AndreasRabe** [comment]
[enmapboxtestdata.zip](https://github.com/ghtmtt/DataPlotly/files/6149318/enmapboxtestdata.zip)

Also note that I get the same error when using the processing algorithm:

```
QGIS version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Build a generic plot' starting…
Input parameters:
{ 'INPUT' : 'C:/source/enmap-box-testdata/enmapboxtestdata/landcover_berlin_point.shp', 'IN_COLOR' : 1, 'IN_COLOR_HTML' : '', 'OUTPUT_HTML_FILE' : 'TEMPORARY_OUTPUT', 'OUTPUT_JSON_FILE' : 'TEMPORARY_OUTPUT', 'PLOT_TITLE' : '', 'PLOT_TYPE' : 0, 'XFIELD' : 'level_1_id', 'YFIELD' : 'level_2_id' }

Traceback (most recent call last):
File "C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_algorithms.py", line 282, in processAlgorithm
standalone_plot_path = plot_instance.buildFigure()
File "C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly_plot.py", line 664, in buildFigure
substr = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Execution failed after 3.71 seconds

Loading resulting layers
Algorithm 'Build a generic plot' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.
```

**Comment by ghtmtt** [comment]
@AndreasRabe Processing algorithm has to be refactored and it is currently broken (we are working on that, but there is already a ticket #209).

I tried with your data and I don't get errors:

![image](https://user-images.githubusercontent.com/2884884/111770738-15b68380-88ab-11eb-9f04-f576914764f3.png)

![image](https://user-images.githubusercontent.com/2884884/111770784-236c0900-88ab-11eb-91f9-baa90297c529.png)

**Comment by AndreasRabe** [comment]
Any ideas what I could try to narrow it down? 
If not, I will wait for the 3.18.1 Windows installer and try again.

**Comment by ghtmtt** [comment]
maybe with a clean QGIS profile

**Comment by AndreasRabe** [comment]
With a clean profile it is working!

**Comment by ghtmtt** [comment]
great. Closing the issue
