### ISSUE TITLE
Overlay two graphics on atlas 

### ISSUE THREAD

**Issue by cesarcorreo** [ghtmtt/DataPlotly#244]
**Describe the bug**

I am trying to overlay two graphics in the atlas. 
I think that should be done from element properties by adding two graphics (screenshot 1).

I have an atlas with 100 points. I am interested in representing in the same graphic the 100 points and in another color (superimposing) the point to which the atlas refers. As you can see in the screenshot 2 I have represented 2 times the two points but in the screenshot 3 you can see all the points. 
I have activated "use only features inside atlas feature" in onli one but it seems that activating this box affects both graphics and not each one independently.
It is a bug or I am wrong about something?
Thanks 

![C1](https://user-images.githubusercontent.com/25932761/102689381-dcb03980-41fd-11eb-962d-b1e245855164.jpg)
----------------------------------------------------------------------
![C2](https://user-images.githubusercontent.com/25932761/102689383-dfab2a00-41fd-11eb-944e-0101b670ebb4.jpg)
----------------------------------------------------------------------------------------------------------
![C3](https://user-images.githubusercontent.com/25932761/102689384-e3d74780-41fd-11eb-96a4-c111c59a44b6.jpg)

**Comment by jdlom** [comment]
I had the same issue with the feature subset. I can't use different feature subsets. When I change the second plot, it overwrites the settings of my first plot.

**Comment by cesarcorreo** [comment]
Thanks for answering. 
I thought I was doing something wrong.
Waiting for the developers comments,

**Comment by SGroe** [comment]
I confirm the issue and implemented a possible solution (see #245)

**Comment by jdlom** [comment]
@SGroe do you need any feedback ? I can find some times tomorrow to test your solution. Thanks anyway

**Comment by SGroe** [comment]
@jdlom yes, please write your feedback in the pull request. Thanks

**Comment by ghtmtt** [comment]
Thanks @SGroe for the code and @jdlom for testing. We will wait your feedback!

**Comment by cesarcorreo** [comment]
> @jdlom yes, please write your feedback in the pull request. Thanks

I wrote the original post. If you need / want I can check it but unfortunately I don't have any programming skills.
I don't know how to install the "new version". 
Ask me or send me the zip file of the pluging if you want. 
Thanks for the work.

**Comment by SGroe** [comment]
> > @jdlom yes, please write your feedback in the pull request. Thanks
> 
> I wrote the original post. If you need / want I can check it but unfortunately I don't have any programming skills.
> I don't know how to install the "new version".
> Ask me or send me the zip file of the pluging if you want.
> Thanks for the work.

https://www.sgroe.at/DataPlotly.zip

**Comment by jdlom** [comment]
This plugin is awesome and having many plots in plot item is very helpful. Thanks for having implemented this functionality.

**Comment by cesarcorreo** [comment]
> > > @jdlom yes, please write your feedback in the pull request. Thanks
> > 
> > 
> > I wrote the original post. If you need / want I can check it but unfortunately I don't have any programming skills.
> > I don't know how to install the "new version".
> > Ask me or send me the zip file of the pluging if you want.
> > Thanks for the work.
> 
> https://www.sgroe.at/DataPlotly.zip

Tested with the same file and now it works perfectly ¡¡¡
Many thanks for the plugin and for the implementation
![Captura de pantalla 2021-02-09 085806](https://user-images.githubusercontent.com/25932761/107333187-67523e00-6ab5-11eb-9258-c5fb2e810db6.jpg)

**Comment by SGroe** [comment]
I am not sure about the Travis errors. Apart from that, it can be merged and released.
