### ISSUE TITLE
No grid / axis shown

### ISSUE THREAD

**Issue by alexguyot** [ghtmtt/DataPlotly#249]
Hi,

Thanks for this great plugin !

I'm submitting what seems to be a bug with the latest QGIS version :
After an update to QGIS 3.18, plots from DataPlotly do not display background grid and axis.
Dataplotly version is 3.7.1 (plugin reinstalled)

Ex : 
![image](https://user-images.githubusercontent.com/23362588/109950668-1234d100-7cdd-11eb-901c-0a92e1fb2cdd.png)

The behaviour is similar whether it is a previously configured plot or a new dataplotly object.

Thanks.

**Comment by ghtmtt** [comment]
confirmed. Could you please share your plotly version? Just open the python console in QGIS and paste the following code line by line:

```
import plotly
plotly.__version__
```

**Comment by ghtmtt** [comment]
this PR #249 has set the background to transparent. In the future we will implement some trivial settings to change the background, axis etc colors. So the behavior you experience is expected.

**Comment by anderson-lactec** [comment]
@ghtmtt , do you have a deadline to insert the new features (to change the background, axix colors, etc) into the composer?

**Comment by ghtmtt** [comment]
not yet, but stay tuned because you will some some huuuge news very soon :)
