### ISSUE TITLE
Small UX issue about panel when opening the dock

### ISSUE THREAD

**Issue by Gustry** [ghtmtt/DataPlotly#267]
**Describe the bug**

Visible on the GIF, the first panel is wrong according to the menu on the left : 
I can reproduce 100%, maybe new QGIS session ?

![dataplotly](https://user-images.githubusercontent.com/1609292/135098757-93f7ec81-b8f9-4484-bdea-600364035855.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 21.04
 - QGIS release [e.g. QGIS 3.10] Master (and also 3.16 I think)
 - DataPlotly release [e.g. 3.0] 3.7.1

**Additional context**

**Comment by ghtmtt** [comment]
yep you are right. should be fixed and a new point 3.8.1 release has been done
