### ISSUE TITLE
Translation of the plugin

### ISSUE THREAD

**Issue by Gustry** [ghtmtt/DataPlotly#272]
**Describe the bug**

There is a `.tx` folder in this repository, so it means a previous transifex setup.
The link on faunalia website about transifex is broken : https://www.faunalia.eu/en/dev/dataplotly

How can we translate the plugin now ?
Is transifex platform removed ?

**Comment by comradekingu** [comment]
Hopefully it can be moved to Weblate.
Happy to help if so :)

**Comment by Gustry** [comment]
I'm aware Transifex is not opensource, but all the CI scripts for updating and fetching translations is included in [qgis-plugin-ci](https://github.com/opengisch/qgis-plugin-ci)
Do you have some experience with weblate @comradekingu ?

**Comment by comradekingu** [comment]
@Gustry I am a top contributor on both. I have zero good experience with Transifex.
Integration for all sorts of systems is available in https://docs.weblate.org/en/latest/vcs.html?highlight=github

**Comment by ghtmtt** [comment]
fixed in https://github.com/ghtmtt/DataPlotly/pull/281
