### ISSUE TITLE
Select features in QGIS display and highlight in Plot

### ISSUE THREAD

**Issue by aloboa** [ghtmtt/DataPlotly#274]
Selecting in the plot (eg scatterplot) automatically highlights points in the QGIS display,
is the reverse possible (selecting in QGIS and highlighting in the scatterplot)?
Note this is not the same as "Use only selected features", as in this case you cannot
see the selected points in the context of the scatterplot.
If this is not currently possible, could this feature be added?

**Comment by ghtmtt** [comment]
Hi @aloboa. I thought long time ago to have a two-way sync between map and plot. But it seems to me that it is impossible to catch a signal from a map and send it to a plotly slot: I don't think plotly canvas is able to do that.

**Comment by aloboa** [comment]
Sad news.
Just in case it could be of any help, RasterDataPlotting let's you do that in raster format (https://raster-data-plotting.readthedocs.io/en/latest/content.html#), albeit not using plotly.
Could this limitation be clear in the definition of the plugin to avoid frustration? GIS users need selecting in the map and visualizing in the plot as much as (or more than) selecting in the plot and visualizing in the map.
