### ISSUE TITLE
Graphics Customization

### ISSUE THREAD

**Issue by Fertuesta25** [ghtmtt/DataPlotly#277]
It would be interesting to be able to perform the following actions:
- Add labels to graphs of bars, lines, points, etc. and be able to configure the font, size, color, etc.
- Disable the Y and X axes.
- Disable chart navigation buttons in map composer.
- Create combined graphs (line graph + bar graph for example).
- Deactivate the graph grid.
- To be able to activate the smooth line option in line graphs.

**Comment by ghtmtt** [comment]
> Create combined graphs (line graph + bar graph for example).

this is already possible. You can easily overlap as many plot types as you want (https://github.com/ghtmtt/DataPlotly#overlapped-plots)

**Comment by Fertuesta25** [comment]
Thanks @ghtmtt, I'll try.

**Comment by ghtmtt** [comment]
@pbessin all the features are certainly feasible. We are thinking to start a crowdfunding campaign with all the feature requests opened!

**Comment by Fenrihr** [comment]
Hello! I would like to add to the order the possibility of reducing margins.

**Comment by ghtmtt** [comment]
this issue is becoming a little bit too confused. I'm closing it and @Fertuesta25 @Fenrihr @pbessin please open atomic issues for other requests (have a look if the request has already been reported)
