### ISSUE TITLE
Histogram Manual Bin 

### ISSUE THREAD

**Issue by ilockerbie** [ghtmtt/DataPlotly#280]
**Describe the bug**
Manual Bin Size in Histogram cannot be set.

**To Reproduce**
Import the attached spreadsheet (drag and drop into QGIS)
Create point layer using Processing Toolbox>Vector creation>Create points layer from table 
Open DataPlotly plugin
  - Select plot type = Histogram
  - Set X field = Value
  - Select/Deselect 'Manual bin size' checkbox (value cannot be changed)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGIS release:  3.22.3-Białowieża
 - DataPlotly release: 3.8.1

[GenerateNormal.xlsx](https://github.com/ghtmtt/DataPlotly/files/8143169/GenerateNormal.xlsx)

**Additional context**
![manual bin checked](https://user-images.githubusercontent.com/32883602/155762567-dfdd3477-6d7c-4dce-b93c-53d06e336046.PNG)
![manual bin unchecked](https://user-images.githubusercontent.com/32883602/155762573-410504dc-1d18-4804-bcb4-d70de1801a70.PNG)

**Comment by ghtmtt** [comment]
cannot confirm. Can you try again?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2884884/163124272-1421793b-a77b-4a60-bfda-3b1c1421bf37.gif)

**Comment by ilockerbie** [comment]
Thanks for getting back to me.  I tried again, and it's still not working
for me.

[image: histogram issue.gif]
[image: Logo] <https://3d-p.com/> [image: Logo]

Ian Lockerbie
Senior Wireless Engineer
D: (403) 930-0866
E: ***@***.***

**Comment by ghtmtt** [comment]
@ilockerbie can you please try with the last release?

**Comment by ilockerbie** [comment]
It seems to be fixed now.

Thanks very much!
