### ISSUE TITLE
Using formulas for legend not working

### ISSUE THREAD

**Issue by rbonnefoi** [ghtmtt/DataPlotly#295]
**Describe the bug**
Dear all,

I am a new user of DataPlotly plugin, which fits to my needs. Thanks for the work.

But I still have a problem in legending subsets : whatever the formula is entered, it always uses the static text writen into the "Legend title" of the plot setup tab.

This is as if the formula was never taken into account. [edit] Except when the formula uses a "static" text, for instance 'test' (without any variable)

Any help / bug correction will be greatly appreciated.

Many thanks.

Remi.

**To Reproduce**
Input any formula for the legend title field

**Screenshots**
As you can see on this screenshot, I set up a formula for the legend title field
![image](https://user-images.githubusercontent.com/12908619/181507340-e4063aba-1323-4847-b085-bbb25cfcda4c.png)

In the formula editor, I can check on the lower left corner that the formula is valid, as the preview displays what I expect
![image](https://user-images.githubusercontent.com/12908619/181509425-3827b6a8-dcef-421f-8255-e7801f0637da.png)

But once the plot created, the legend still displays the "hard static" legend.
![image](https://user-images.githubusercontent.com/12908619/181510414-0c55214f-b6f0-4abc-8a04-6f24dde652e7.png)

**Desktop (please complete the following information):**
 - OS: W11 
 - QGIS release: 3.26.1
 - DataPlotly release: 3.9

**Comment by ghtmtt** [comment]
confirmed. I'm actually thinking if we really need to have a data defined legend button. What are the real life example? Legend title is always a single string and it does not make any sense to evaluate it against a layer field.

A simple text box will be enough IMHO.

@Gustry do you have any use case for this?

**Comment by rbonnefoi** [comment]
Hi @ghtmtt,

Thanks for the check.

I think this option is mandatory when the "feature subset" is active, which is what I need. Or I may have not understood the way it works and the relationships between both.

Regards.

**Comment by ghtmtt** [comment]
still with a feature subset, why do we need a legend text that is taking something for the data? I see this plot option static and not dynamic

**Comment by rbonnefoi** [comment]
I think I don't understand the subset feature, or it doesn't work as expected.

In my case, I have a point layer with 3 main fields :

- category, which is used for subset feature (I want to be able to distinguish the plots according to each category)
- x, used for the x-axis plot coordinate
- y, used for the y-axis plot coordinate

When I try to plot this data through a scattered plot, I am unable to make the subset feature work. All the points behave to the same plot (same color, one legend, and no "pen up" between to subset, the plotting is "continuous" between the different subsets).

You'll find attached a test layer and the corresponding (unexpected) plot.

Many thanks for the help
![plot](https://user-images.githubus
[dataplotly subset test layer.zip](https://github.com/ghtmtt/DataPlotly/files/9430682/dataplotly.subset.test.layer.zip)
ercontent.com/12908619/186845118-c204e2a1-0926-423e-8585-f4d4a4e692d0.png)
.

**Comment by ghtmtt** [comment]
feature subset works in the same way as the QGIS native filter: e.g. if you have a layer with all the world countries, you can use the feature subset to filter only the countries of Europe.

So feature subset and data defined legend are 2 very different things.

**Comment by rbonnefoi** [comment]
Ok thanks. I had in mind it was a subsetS feature (I mean a grouping feature) not a filter feature.

I think such a grouping feature would be very useful.
