### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by dahlalex** [ghtmtt/DataPlotly#306]
I got the following error message when I tried to install the plugin in QGIS 3.26.3-Buenos Aires.

"Couldn't load plugin 'DataPlotly' due to an error when calling its classFactory() method 

TypeError: is not a generic class "

Any suggestions?

**Comment by ghtmtt** [comment]
this is really weird. What version of QGIS are you using? Did you try with a clean profile?

**Comment by dahlalex** [comment]
Thank you for your answer. You're completely right. The problem had nothing to do with the plugin. It was with the profile folder.
 I found this link very useful: [Installation problem](https://groups.google.com/g/aequilibrae/c/MtY-dmVsqko).

**Comment by ghtmtt** [comment]
great that you solved the problem
