### ISSUE TITLE
Color scatter plot from attribute

### ISSUE THREAD

**Issue by ic144** [ghtmtt/DataPlotly#311]
**Describe the solution you'd like**
I would like the option to color lines or points in a scatter plot based on an attribute. Example: I have time series in different locations and would like to compare these in a single plot. Plotly has the option to assign (random) colors based on an attribute.

**Describe alternatives you've considered**
An alternative would be to add a column with colors to the attribute table 

**Additional context**
Current in QGIS:
![afbeelding](https://user-images.githubusercontent.com/99961361/214270579-251b3ef8-9bf3-4bc4-98e4-6368d637c77a.png)
Possible in Python:
![afbeelding](https://user-images.githubusercontent.com/99961361/214271177-711a83c1-78d2-462b-b448-1a8d6c4504bc.png)

**Comment by ghtmtt** [comment]
thanks not possible yet because the standard plotly API uses plotly.express (that offers this option). You can use the Processing algorithm for that

**Comment by ic144** [comment]
Thanks! Would that be this Processing algorithm?
https://github.com/ghtmtt/DataPlotly/tree/master/DataPlotly/processing

**Comment by ghtmtt** [comment]
yes exactly

**Comment by ghtmtt** [comment]
closing this issue, please reopen if necessary
