### ISSUE TITLE
Color chart with color symbology

### ISSUE THREAD

**Issue by MC88PS** [ghtmtt/DataPlotly#320]
Hello, I would need to create a graph that shows the exact same colors of the symbology in the legend ... specifically, the objects are lines (no polygons)!

 - OS: Windows 11 Pro
 - QGIS release: 3.22.8
 - DataPlotly release: 4.0.0

**Comment by ghtmtt** [comment]
you can use the data defined property with the custom function. See the related PR gif: https://github.com/ghtmtt/DataPlotly/pull/288

**Comment by MC88PS** [comment]
I'm sorry but the function doesn't work for me

**Comment by ghtmtt** [comment]
can you please give more details? Which plot are you using? Which dataset?

**Comment by MC88PS** [comment]
I have categorized some lines with this set of values
![immagine](https://github.com/ghtmtt/DataPlotly/assets/133139417/5cecebbb-d65f-40c1-98a3-aa1d84641aa0)

In the color of the symbol I go to edit and insert the function
![immagine](https://github.com/ghtmtt/DataPlotly/assets/133139417/daa7b0ef-bbe9-42c3-8bdb-2603bc6f74a6)
![immagine](https://github.com/ghtmtt/DataPlotly/assets/133139417/52a6ac53-b14d-416e-9289-3616404cda37)

In the expressions tab I insert the new function but it doesn't seem to work
![immagine](https://github.com/ghtmtt/DataPlotly/assets/133139417/9454ed6a-78cd-431b-a2b6-251dede87f34)

**Comment by ghtmtt** [comment]
you have to use the function within the `DataPlotly` box

**Comment by MC88PS** [comment]
yes i use the one inside of DataPlotly box

**Comment by ghtmtt** [comment]
you are adding a parameter that is not needed. Just try ` get_symbol_colors()`

**Comment by ghtmtt** [comment]
you have an error when you are using the expression. Can you please have a look at it?

**Comment by MC88PS** [comment]
This is a function...it's ok?

from qgis.utils import qgsfunction
from qgis.core import QgsRenderContext


@qgsfunction(args='auto', group='DataPlotly')
def get_symbol_colors(feature, parent, context):
    """
        Retrieve the color of each category as html code. You can use this function
        to set the plot items (pie slices, bars, points, etc) to the same color
        of the feature visible in the map.
        <h4>Syntax</h4>
        <p>
            get_symbol_colors() -> '#da1ddd'
        </p>
    """

    layer = context.variable('layer')
    renderer_context = QgsRenderContext()
    renderer = layer.renderer()
    renderer.startRender(renderer_context, layer.fields())

    symbols = renderer.originalSymbolsForFeature(feature, renderer_context)

    if symbols:
        color = symbols[0].color().name()
    else:
        color = ()
    
    renderer.stopRender(renderer_context)

    return color

**Comment by ghtmtt** [comment]
no I mean that when you are using the function, in the bottom left corner you have an error message that you can click and that can explain what is going on

**Comment by MC88PS** [comment]
ok sorry

![immagine](https://github.com/ghtmtt/DataPlotly/assets/133139417/6ad27a70-eeef-4757-b310-05383b52fa85)

**Comment by MC88PS** [comment]
Problem solved! That was the reason!
Thank you very much!!
