### ISSUE TITLE
Catch the exception when panda is required

### ISSUE THREAD

**Issue by Gustry** [ghtmtt/DataPlotly#331]
**Describe the bug**
Install Dataplotly on a computer where there isn't panda installed

```
QGIS/QGIS3/profiles/formation/python/plugins/DataPlotly/processing/dataplotly_scatterplot.py", line 43, in 
    import pandas as pd
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pandas'
```

It seems only one file requires panda, so it seems easy to check if panda is installed before adding the processing algorithm

**Desktop (please complete the following information):**
 - OS: Ubuntu LTR 22.04
 - QGIS release 3.28
 - DataPlotly release : latest, when installing

**Comment by ghtmtt** [comment]
@Gustry can we close this issue?

**Comment by Gustry** [comment]
My bugfix is only to avoid the Python exception, but it's not indicating the end user that some features are missing. (I'm considering that logging is not enough, there isn't any UI hint that some features are missing in dataplotly and the package must be installed manually)

Up to you.

**Comment by ghtmtt** [comment]
related to https://github.com/ghtmtt/DataPlotly/pull/332
