### ISSUE TITLE
Attempting to activate plugin crashes QGIS

### ISSUE THREAD

**Issue by markstos** [ghtmtt/DataPlotly#343]
**Describe the bug**

Attempting to activate plugin reliably crashes QGIS and produces this output:

```
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method QWebPage::repaintRequested(QRect)
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QObject::connect: No such signal QWebFrame::iconChanged()
Warning: QObject::connect: No such signal QWebFrame::urlChanged(QUrl)
Warning: QObject::connect: No such signal QWebPage::loadStarted()
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebPage::statusBarMessage(QString)
Warning: QObject::connect: No such signal QWebPage::linkClicked(QUrl)
Warning: QObject::connect: No such signal QWebPage::selectionChanged()
Warning: QObject::connect: No such signal QWebPage::microFocusChanged()
munmap_chunk(): invalid pointer
fish: Job 1, 'qgis' terminated by signal SIGABRT (Abort)
```

**To Reproduce**
1. Go to Plugin Manager
2. Click on Activate Plugin checkboj
4. See QGIs crash. 

**Desktop (please complete the following information):**
 - OS: Arch Linux, Kernel 6.6.3. Sway version 1.8.1.
 - QGIS release: 3.34.1-Prizren
 - DataPlotly release:

❯ paru -Qi python-plotly
Name            : python-plotly
Version         : 5.18.0-1

**Additional context**
Attempting to load the `qgis2web` plugin also crashes QGIS in my environment. 

There appears to be some expectation about some QT package and version that's not try in my environment.

**Comment by markstos** [comment]
I resolved my crashing problem by installing `qgis` using `conda`, which includes all the dependencies to make this work. 

I recommend simply not trying to support all Linux distros, but rather just list ones you support, and document that users of other distros are advised to install use QGIS via `conda`.

**Comment by ghtmtt** [comment]
thanks for the reporting. The plugin runs on all the Linux distros, probably your unresolved dependencies caused the crash.

I'm closing the issue. Thanks again
