### ISSUE TITLE
Missing Plot Types for the DataPlotly Plug-in

### ISSUE THREAD

**Issue by SeaWombat** [ghtmtt/DataPlotly#347]
Hi,

I have DataPlotly v 4.1.0 installed with QGIS 3.36.1 on a Windows 11 PC. Installing the plug-in produced no errors, and the plug-in is enabled. But it seems that only the Scatter Plot is enabled and functioning (see attached screenshots). I uninstalled and re-installed the plug-in, but I still have the problem. I also downgraded my version of QGIS to QGIS v3.34 LTR and installed DataPlotly. It was still missing all the plot types except for the Scatter Plot.

I checked to see if I was missing dependencies, and  numpy,  pandas, and plotly appear to the there. I'm unsure if I am missing some of the dependencies. I've attached a text file listing what's installed in my QGIS python environment.

I'm hoping this is just a noob issue and I missed something obvious. Any ideas?

Thanks.

--Dave

[QGIS installed packages.txt](https://github.com/ghtmtt/DataPlotly/files/14805718/QGIS.installed.packages.txt)
![QGIS screenshot](https://github.com/ghtmtt/DataPlotly/assets/37672114/6ec4cec0-20c9-442d-9474-ff5c8084897e)
![scatter plot](https://github.com/ghtmtt/DataPlotly/assets/37672114/9f21c21a-520e-4521-ac22-a70a6c24ce8d)

**Comment by ghtmtt** [comment]
that's correct. At the moment in the Processing interface, only scatter plots are available. If you need more plots you have to use the standard DataPlotly UI where all the other plot types are available!

**Comment by SeaWombat** [comment]
Hi Matteo,

Thanks so much for the speedy response.

Where is the standard DataPlotly UI found in the QGIS interface? I looked under the Plugins dropdown menu, and it doesn't show in the Plugins dropdown menu (but shows as installed under installed plugins) or in the other menus. I only found the scatter plot by searching the plugins browser.

--Dave
________________________________

**Comment by SeaWombat** [comment]
Hi Matteo,

Please ignore my last email. I found the interface by loading the plugin toolbar in QGIS. It's right there in front of god and everybody. I will be happily plotting now. Grazie mille for creating this plugin.

--Dave
________________________________
