### ISSUE TITLE
Show value in top of bar or point in layout map

### ISSUE THREAD

**Issue by Newton787** [ghtmtt/DataPlotly#352]
The plugin works well, but not showing the value kills the whole purpose of the tool.

I could use DataPloty in my Atlas, but without showing the values, I am being forced to build bar graphs by hand using the size and position features. I believe this is a high-priority feature, otherwise it is only generating colored lines and bars that do not say much.

I confess that I am a little irritated by the absence of this feature in a plugin so recommended by the community.

**Comment by pcav** [comment]
You have two ways of eliminate your irritation:
* Develop this feature yourself 
* Pay someone to do it for you.
Cheers.

**Comment by nabazgharib** [comment]
@Newton787 on layout option tabs, select a field on (Additional hover label) list, and click on Update plot to see the values.
![image](https://github.com/user-attachments/assets/e27dc138-dd1e-4f44-b4a4-166980b557b7)

**Comment by ghtmtt** [comment]
thanks @nabazgharib for the explanation!
