### ISSUE TITLE
QGIS 3.34.13 - Unable to load the ‘DataPlotly’ extension causes an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by pbessin** [ghtmtt/DataPlotly#363]
Hello,

I am a regular user of DataPlotly which is really great to easily visualize data in a GIS !

I just upgrade my QGIS versions to QGIS 3.34.13 LTR and Q.GIS 3.40.1 from OSGeo4W. However, the DataPlotly Plugin is not working anymore with the following message

--------------------------------------------------------------------------------------------------------------
Unable to load the ‘DataPlotly’ extension causes an error when calling its classFactory() method 

TypeError: expected string or bytes-like object, got 'NoneType' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Paul Bessin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\__init__.py", line 33, in classFactory
    from .data_plotly import DataPlotly
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Paul Bessin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly.py", line 36, in 
    from DataPlotly.processing.dataplotly_provider import DataPlotlyProvider
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Paul Bessin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_provider.py", line 27, in 
    from DataPlotly.processing.dataplotly_scatterplot import DataPlotlyProcessingScatterPlot
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Paul Bessin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_scatterplot.py", line 43, in 
    import pandas as pd
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\__init__.py", line 26, in 
    from pandas.compat import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\compat\__init__.py", line 27, in 
    from pandas.compat.pyarrow import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\compat\pyarrow.py", line 10, in 
    _palv = Version(Version(pa.__version__).base_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\util\version\__init__.py", line 341, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

Version de Python : 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.13-Prizren Prizren, 222b5995 

-------------------------------------------------------------------------------------------

I already tried to reinstall DataPlotly from QGIS Extension menu and from a .zip file but the bug is the same.

Desktop (please complete the following information):
 - OS: Windows 10 Eduation version 22h2, build 19045.5131
 - QGIS release : 3.34.13-Prizren Prizren, 222b5995 installed with OSGeo4W
 - Python release : 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] installed with OSGeo4W
 - DataPlotly release : 4.2.0

Several other users of my labs experimented the same issue with QGIS version higher than QGIS 3.24 or 3.28.

I am available for any further information.

Best regards,

Paul

**Comment by LoreForna** [comment]
Same problem for me

**Comment by grantboxer** [comment]
Same problem as well

**Comment by matematto** [comment]
Same here :-(

**Comment by ghtmtt** [comment]
I think the error is pandas related. Could you please test the following code in the python console within QGIS?

```python
import pandas as pd
```

If this is failing too (I tested on a Windows virtual machine), than we got some issues with the pandas packaging.

@agiudiceandrea I saw a similar problem here https://github.com/qgis/QGIS/issues/59776. Do you think this is a similar problem?

**Comment by ghtmtt** [comment]
so it's `pyarrow` related and not `pandas` issue? Or what you described above (to uninstall or change the line) can be done also in `apps\Python312\Lib\site-packages\pandas\__init__.py`?

**Comment by grantboxer** [comment]
I have re-installed python3-pyarrow using the network installer and updated the file to version 15.02.01 and this seems to fix the problem. Maybe others can check this works for them as well?

**Comment by pbessin** [comment]
> @ghtmtt and @agiudiceandrea, @grantboxer, the following solution which you proposed is working :
>* uninstall the python3-pyarrow 0.0.0-1 OSGeo4W package and manually remove the "pyarrow" folder in  `apps\Python312\Lib\site-packages\`
>* reinstall pyarrow 15.0.2 from OsGeo4W if needed to other processes in QGIS

> Thank you for your help !!

**Comment by agiudiceandrea** [comment]
> I have re-installed python3-pyarrow using the network installer and updated the file to version 15.02.01 and this seems to fix the problem. Maybe others can check this works for them as well?

Yes, even this workaround will make pandas to work. Anyway the importing of pyarrow will generate the "ImportError: DLL load failed while importing lib: The specified procedure could not be found." error.

**Comment by agiudiceandrea** [comment]
The issue has been fixed with https://github.com/jef-n/OSGeo4W/commit/cfc6b5f4084cf373a90d5766a6f54f37eceed894.
The updated python3-pyarrow version 17.0.0-1 OSGeo4W package contains the fix and makes pyarrow, pandas and geopandas work as expected.

**Comment by ghtmtt** [comment]
great, thanks!

**Comment by FredericFournier** [comment]
Thank for your response, it seems to work fine

**Comment by pigreco** [comment]
@ghtmtt @agiudiceandrea 
the problem reoccurred in 3.34.15 that I just installed from OSGeo4W

**Comment by pigreco** [comment]
> [@pigreco](https://github.com/pigreco), is it the same error message? With QGIS 3.34.15 and 3.40.3, Jürgen also updated a lot of packages.

Impossibile caricare il plugin 'DataPlotly' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\__init__.py", line 33, in classFactory
    from .data_plotly import DataPlotly
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly.py", line 32, in 
    from DataPlotly.gui.dock import DataPlotlyDockManager
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\gui\dock.py", line 19, in 
    from DataPlotly.gui.plot_settings_widget import DataPlotlyPanelWidget
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\gui\plot_settings_widget.py", line 49, in 
    from qgis.PyQt.QtWebKit import QWebSettings
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\PyQt\QtWebKit.py", line 24, in 
    from PyQt5.QtWebKit import *
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'


Versione Python: 3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.34.15-Prizren Prizren, 386f2583 

Percorso Python:
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Split-Lines-By-Points-main
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\ext-libs\duckdb
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\ext-libs
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gensimplot
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gensimplot
.

**Comment by agiudiceandrea** [comment]
It looks like an issue that will break various other plugins using QtWebKit.
Ping @jef-n.

**Comment by agiudiceandrea** [comment]
https://trac.osgeo.org/osgeo4w/ticket/866

**Comment by agiudiceandrea** [comment]
@pigreco, the issue should be fixed now updating the `python3-pyqt5` package to version 5.15.11-2.

**Comment by pigreco** [comment]
> the issue should be fixed now updating the `python3-pyqt5` package to version 5.15.11-2.

thank you very much, solved!

**Comment by ghtmtt** [comment]
thank you all for reporting and explaining the solution!
