### ISSUE TITLE
Error using DataPlottly with QGIS 3.40.1

### ISSUE THREAD

**Issue by FredericFournier** [ghtmtt/DataPlotly#366]
**Describe the bug**
Since I upgraded to QGIS 3.40.1, I get the following error message when I want to activate the DataPlottly plugin (4.2.0)

**To Reproduce**
1. Go to 'Plugins'
2. Go to 'Installed'
3. Click on 'DataPlottly' to activate the plugin
4. See error with screenshots below (TypeError: expected string or bytes-like object, got 'NoneType')
5. Reinstall plugin
6. Same error

**Screenshots**
See attached file or
![DataPlottly error](https://github.com/user-attachments/assets/b0aa3a21-c2da-47de-9ba8-a05990b3868b)

**Comment by ghtmtt** [comment]
pyarrow upstream issue not related to the plugin. Please see https://github.com/ghtmtt/DataPlotly/issues/363#issuecomment-2559945347
