### ISSUE TITLE
Create Processing module

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#38]
Could be worth to have also a Processing module that calls DataPlotly API and creates the plot, something like:
![selection_002](https://user-images.githubusercontent.com/2884884/29568926-2f7c17ac-8752-11e7-8e4c-d159a292096c.png)

the method should create some kind of output (dictionary, json...) that will be elaborated by a method of the plugin. 
Finally a `QWebView` should be opened (with the `js` interaction)

**Comment by ghtmtt** [comment]
Definitely not easy right now. A method is on the road (see https://github.com/ghtmtt/DataPlotly/blob/standalone/data_plotly_dialog.py#L880) and the last sets of commit in the **standalone** branch (42425c5d78ecf88fa5e691b33d830337ac9e91ea).

Right now it is possible and it is very easy to pass a dictionary with some default values and call the method `showPlot`. For example, with a `QgsVectorLayer` loaded in the legend and `DataPlotly` loaded in QGIS:

vl = iface.activeLayer()
# import the plugin
from qgis.utils import plugins
# create the instance of the plugin
my = plugins['DataPlotly']

# create a dictionary with some entries
dq = {}
dq['plot_type'] = 'scatter'
dq["layer"] = vl
dq['plot_prop'] = {}
dq['plot_prop']['x'] = [i["O2"] for i in vl.getFeatures()]
dq['plot_prop']['y'] = [i["EC"] for i in vl.getFeatures()]
dq['plot_prop']['marker'] = 'markers'
dq['plot_prop']['x_name'] = 'O2'
dq['plot_prop']['y_name'] = 'EC'
dq['plot_prop']['custom'] = 'O2'
dq['layout_prop'] = {}
dq['layout_prop']['legend'] = True

# call the method that opens the dialog and load the created plot
my.loadPlot(dq)

**Comment by ghtmtt** [comment]
Besides creating the DataPlotly Processing module so that it calls the Dialog and the user can update the parameters in a second moment, it could be very very useful to have some DataPlotly Processing code that outputs some `html` data as plots. In this way DataPlotly can be used also in the Modeler.

**Comment by mdouchin** [comment]
I would like to develop this feature. Do you have any pointer to specific usefull classes ?
Happy end of year !

**Comment by ghtmtt** [comment]
What a good news @mdouchin, thanks for taking interest in this feature. 

I stopped to develop this feature some months ago.. Anyway, some information of the old progress:

* the branch `processing` https://github.com/ghtmtt/DataPlotly/tree/processing (needs rebasing) has the subfolder `dataplotly_processing` that allow to manage the plugin as a Processing provider (it works)
* I've made some attempts and create a method of the main plugin class here: https://github.com/ghtmtt/DataPlotly/blob/master/data_plotly_dialog.py#L1116 but there have been problems and I gave up

Anyway, my idea was to add a kind of basic configuration of each plot in Processing (e.g. ScatterPlot, BoxPlot,..) but without complicated customization (like the picture of this issue).
Then, when run, Processing opens the plugin itself: in this way the user can adjust some other customization not present in the Processin dialog.

Anyway, this could be overkilling and worst, this algorithm (thought in this way) cannot be used within the Processing modeler.

So feel free to open a discussion :) I'm open to all kind of ideas

Thanks again for the interest!

**Comment by mdouchin** [comment]
Thanks for your reply. I think 

* we should indeed add a basic configuration, not the full options.
* we should only export a full HTML output, with no opening of the "real" dataplotly dock, and no interaction with the map or features. This way, the HTML output will be usable in the modeler. If the user wants the full and rich interactive output, he should use the plugin instead IMHO

**Comment by mdouchin** [comment]
Could you pass some hint to run QGIS 3 ready for developping dataplotly ? I tried with the Camptocamp docker image (with qgis 3), but I get the error

`ModuleNotFoundError: No module named 'PyQt5.QtWebKit'`

Hint : to test the docker image:

`docker run --rm -ti -e DISPLAY=unix${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix -v ${HOME}:${HOME} camptocamp/qgis-server:3 /usr/local/bin/start-client.sh`

**Comment by ghtmtt** [comment]
Hey, I think you have to install also ``python3-pyqt5.qtwebkit`` (even in the docker image). Else, if you compile qgis3 and you have that module installed you shoudn't have any trouble (I'm doing exactly this way).

**Comment by ghtmtt** [comment]
> we should indeed add a basic configuration, not the full options.

totally agree

> we should only export a full HTML output, with no opening of the "real" dataplotly dock, and no interaction with the map or features. This way, the HTML output will be usable in the modeler. If the user wants the full and rich interactive output, he should use the plugin instead IMHO

again, +1. Including DataPlotly in Processing make sense only if it is usable in the Modeler, else the use can use the plugin itself

**Comment by mdouchin** [comment]
PR #65 is a good start :)

I decided to let your methods loadPlot and showPlot (but rename them) in order to let you continue to test inside the python console.

Il moved the default dictionnary (previously in the showPlot method) to the data_plotly_plot class, which uses it in the init

I decided to create a single alg with few parameters, not as many algs as plot types. So you can chosse the layer, plot type (among a short list for now), plot title, X and Y fields

**Comment by ghtmtt** [comment]
with 2cdca78bfce7e4cd4fac287d643b3603be6a6694 we can close this issue and opening other related issues
