### ISSUE TITLE
Add CI and testing suite

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#46]
In a future automated tests have to be added. Not a simple process (especially with Travis). Some references:

https://snorfalorpagus.net/blog/2014/01/04/writing-unit-tests-for-qgis-python-plugins/
https://github.com/boundlessgeo/qgis-testing-environment-docker
https://boundlessgeo.com/2016/07/qgis-continuous-integration-testing-environment-for-python-plugins/

**Comment by nyalldawson** [comment]
Implemented
