### ISSUE TITLE
import external files

### ISSUE THREAD

**Issue by pigreco** [ghtmtt/DataPlotly#50]
it would be useful to analyze vectors not present in the TOC; would it be easy to add a button as in the figure?
![image](https://user-images.githubusercontent.com/7631137/31382040-a8664900-adb6-11e7-955e-30ef34ae1d24.png)

**Comment by ghtmtt** [comment]
it should not be a problem to add also this feature. I'm just thinking: is it really worth? do you think users can have the need to create plot also from external files?

**Comment by pigreco** [comment]
@ghtmtt 
My only idea is, I do not know if other users need to plot external resource charts.
If you have many similar layers and you want to figure out which one to load according to some parameter, I think it will be useful.

**Comment by ghtmtt** [comment]
@pigreco some news.. not so easy to implement your request. When loading an external file the fields are not automatically loaded in the x and y comboboxes. I think the easiest way is to load the file into QGIS so the plugin can use the internal API to load the fields.

**Comment by pigreco** [comment]
@ghtmtt OK thanks!
