### ISSUE TITLE
Manual initial load doesn't show properly 

### ISSUE THREAD

**Issue by leonmvd** [ghtmtt/DataPlotly#60]
First time I open the manual it doesn't show properly, after right-click and reload it looks fine. This happens after opening each page.
![screen shot 2017-12-01 at 12 56 25 pm](https://user-images.githubusercontent.com/9214202/33482004-4c43f082-d697-11e7-850e-f515f5e1914f.png)

Using macOS (10.12.6 (16G1036)) qgis home-brew install 
Version info 

![screen shot 2017-12-01 at 12 59 34 pm](https://user-images.githubusercontent.com/9214202/33482041-828834b4-d697-11e7-899b-949ce65ad3ea.png)

**Comment by ghtmtt** [comment]
Do you tried also with different languages? That's weird because I cannot replicated the issue on my linux machine. What if you uninstall and re-install the plugin?

**Comment by ghtmtt** [comment]
@leonmvd have you tried also with the last release (1.2.2)?

**Comment by ghtmtt** [comment]
@leonmvd is this issue still present?

**Comment by leonmvd** [comment]
Yes, I just reïnstalled QGIS 2,99 and the plugin (1.2.3). Same problem persists.

**Comment by ghtmtt** [comment]
I cannot reproduce the error (Linux and Windows). Are your loading QGIS in Dutch or in English?

**Comment by ghtmtt** [comment]
closing for not feedback. @leonmvd reopen if necessary!
