### ISSUE TITLE
Plotly library not bundled

### ISSUE THREAD

**Issue by timlinux** [ghtmtt/DataPlotly#62]
After installing on QGIS 2.99 on MacOS I get:

```
Couldn't load plugin 'DataPlotly' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'plotly' 
Traceback (most recent call last):
  File "/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 34, in classFactory
    from .data_plotly import DataPlotly
  File "/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 30, in 
    from DataPlotly.data_plotly_dialog import DataPlotlyDockWidget
  File "/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_dialog.py", line 36, in 
    import plotly
  File "/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'plotly'


Python version: 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] 
QGIS version: 2.99.0-Master Master, ab859c9bdf 

Python Path:
/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/plugins/processing
/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python
/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/plugins
/Users/timlinux/dev/cpp/QGIS-QtCreator-Build/output/bin/$PYTHONPATH
/usr/local/opt/gdal2-python/lib/python3.6/site-packages
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pycharm-debug-py3k.egg
/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

I guess a good solution would be to instruct in the plugin description that the user should install the Plotly library, or (nicer for user maybe) to bundle plotly in with the plugin.

**Comment by ghtmtt** [comment]
Hi @timlinux. Thanks for pointing out the problem. Actually only Linux and OSX users could experience this problem. @jef-n bundled the library within the Windows installer (thanks again!).

I don't have any experience in bundling packages with the plugin, I'll dig into it.

**Comment by vestlink** [comment]
Have you tried:

sudo python3.6 -m pip install plotly

**Comment by vestlink** [comment]
It chrashes though when you try to use anything else but the Scatter Plot

**Comment by ghtmtt** [comment]
@vestlink do you have updated the plugin to the last version? Which OS and QGIS version are you using?

**Comment by vestlink** [comment]
i was using the 3.0.0 on osx

**Comment by vestlink** [comment]
it works now after the plugin was updated

**Comment by ghtmtt** [comment]
@timlinux I'll close this issue because plotly, even if not bundled with OSX and Linux it is with Windows (the painful part of the installation process).

Also: bundling the library would make the plugin too big (> 20MB). I'm following the discussion in dev list: https://lists.osgeo.org/pipermail/qgis-developer/2018-July/053890.html

Reopen if necessary! Thanks

**Comment by achiradiroti** [comment]
Hi, am getting the same error in Win 10 Pro and QGIS 3.22.10 (also tried with Qgis 3.26.2) I have tried reinstalling of course. It then gets disabled as it crashes QGIS. Any clue?

**Comment by ghtmtt** [comment]
you don't have pandas installed. I believe you installed QGIS with the OSGEO4W installer, just open it again and in teh advanced configuration search and install the missing package(s)

**Comment by achiradiroti** [comment]
ops, I had assumed pandas was installed along with QIS by default: now it works nicely. Many thanks

**Comment by jef-n** [comment]
On Thu, 23. Feb 2023 at 02:13:43 -0800, Chiara Dorati wrote:
> ops, I had assumed pandas was installed along with QIS by default: now it works nicely. Many thanks

Only if you install qgis-full - it's an optional dependency as QGIS itself
doesn't need it.

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/

**Comment by ghtmtt** [comment]
thanks for the clarification @jef-n!
