### ISSUE TITLE
match plot colors to layer styles

### ISSUE THREAD

**Issue by davidnfox** [ghtmtt/DataPlotly#71]
Would it be possible to link plot colors to feature symbols, for example using the "symbol_color" expression?  This would facilitate embedding plots onto maps.

**Comment by ghtmtt** [comment]
you can use the data defined button to overwrite the single color for all feature and define a color manually for each feature. DataPlotly supports all the color variables of QGIS (hex codes, etc ). Alternatively you can add a column and define a color (e.g. hex code) for each feature and use again the data defined button

**Comment by ghtmtt** [comment]
@davidnfox was the suggestion useful? Can I close the ticket?

**Comment by ghtmtt** [comment]
If you want to match symbol colors from the layer, the plugin accepts also a HEX string, like `#cccc00`. And then use the datadefined button to style plot features:

![selection_125](https://user-images.githubusercontent.com/2884884/37150596-94f5dfd4-22d2-11e8-80da-7a36afe59669.png)

**Comment by davidnfox** [comment]
Thanks, I'll explore the hex codes further
