### ISSUE TITLE
jsscripts from CDN

### ISSUE THREAD

**Issue by merkato** [ghtmtt/DataPlotly#72]
Right now js scripts libraries polyfill and plotly finks to user qgis profile directory. 

It will be very convenient, if we can use CDN versions ( for example `<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>` - as in https://plot.ly/javascript/getting-started/#plotlyjs-cdn )

**Comment by ghtmtt** [comment]
Having both ``plotly`` and ``polyfill`` locally allows to work with DataPlotly also without an Internet connection, this is the only reason why these files are shipped with the plugin.

**Comment by merkato** [comment]
Maybe checkbox, for selecting that these libraries should be CDN'ened or local for exporting html. 

Really appreciating your work for this plugin !!
Thanks :) :+1:

**Comment by ghtmtt** [comment]
mmm not so straightforward I think. It might be confusing for other people to choose between these different options. 

Glad you appreciate the plugin ;)

**Comment by ghtmtt** [comment]
closing this issue. Feel free to reopen it if you think it is worth to. Thanks for testing and for reporting suggestions
