### ISSUE TITLE
Add DataPlotly to Layout Composer

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#76]
These would be a huge step forward, but difficult to implement. Some ideas:

1. a button like the currents ``Add shape`` where the user can drag a rectangle for the plot area
2. reuse the existing widget (or some parts of it) and put a dock window like the atlas one
3. generate an image (static else a webbrowser is needed and is nonesense in this case) with the plot type and all the parameters
4. would be great to have plot(s) updated depending on atlas features (maybe related to #75 that 's, filtering the plot depending on the mapcanvas returned by the atlas)

a prototype of @nyalldawson (so much thanks for this)

```python
class MyItemType(QgsLayoutItem):
    
    def __init__(self, layout):
        super().__init__(layout)
        
    def draw(self, layout_render_context):
        qpainter = layout_render_context.renderContext().painter()
        # draw using qpainter
        # render using QWebPage
        

class my_item_metadata(QgsLayoutItemAbstractMetadata):
    
    def __init__(self):
        super().__init__(QgsLayoutItemRegistry.PluginItem + 46647, 'my awesome item')
    
    def createItem(self, layout):
        return MyItemType(layout)
        

class my_item_gui_metadata(QgsLayoutItemAbstractGuiMetadata):
    
    def __init__(self):
        super().__init__(QgsLayoutItemRegistry.PluginItem + 46647, 'my awesome item')
    
    def creationIcon(self):
        return QIcon('asdasdasdas.svg')
        
    def createItemWidget(self, item):
        # must render your item's config widget
        return MyItemConfigWidget(item)
        
        
QgsApplication.layoutItemRegistry().addLayoutItemType(my_item_metadata())
QgsGui.layoutItemGuiRegistry().addLayoutItemGuiMetadata(my_item_gui_metadata())
```

**Comment by anitagraser** [comment]
I've successfully used the HTML code from DataPlotly in an HTML item.

**Comment by ghtmtt** [comment]
Hi Anita. Well that's good news! But stay tuned because we are planning to extend DataPlotly as a *real* layout composer plugin. Se no more need to ugly workaround like copying and pasting code in an html frame ;)

**Comment by haubourg** [comment]
@nyalldawson just tested. Hat's OFF!

**Comment by ghtmtt** [comment]
thanks @haubourg for testing the new feature. I think this super old issue can be slowly closed. @nyalldawson?

**Comment by nyalldawson** [comment]
I'll let you do the honours @ghtmtt 😁

**Comment by ghtmtt** [comment]
thanks to all the backers, we can finally close this old standing feature request.
