### ISSUE TITLE
QVariant object is not subscriptable...

### ISSUE THREAD

**Issue by klakar** [ghtmtt/DataPlotly#78]
Ubuntu 18.04
QGIS 3.2

Message from QGIS:

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 35, in classFactory
    return DataPlotly(iface)
  File "/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 59, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
QGIS version: 3.2.0-Bonn Bonn, bc43194 

Python sökväg:
/usr/share/qgis/python
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/klakar/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/klakar/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/home/klakar/spinndisk/qgis

**Comment by ghtmtt** [comment]
that's really weird.. could you try to run this code `locale = QSettings().value('locale/userLocale')[0:2]` in the QGIS python console and print the result of `locale`?

**Comment by klakar** [comment]
>>>locale = QSettings().value('locale/userLocale')[0:2]
>>>print(locale)
sv

**Comment by ghtmtt** [comment]
still weird.. works for me in different languages and you are the only one with this problem. Would you please try to delete the entire `DataPlotly` folder from the plugin directory and reinstall the plugin?

**Comment by klakar** [comment]
Oops, have been away from the computer...
Yes, it works now.
