### ISSUE TITLE
graphics in version 3.2

### ISSUE THREAD

**Issue by Zahar1985** [ghtmtt/DataPlotly#79]
does not build graphics in version QGIS3.2

**Comment by Zahar1985** [comment]
Hello. Windows 7 (32). No graph is created. I tried to create it on another computer on version 3.0.0 and in 3.0.3. Everything turned
![1](https://user-images.githubusercontent.com/34969975/43254878-0239481c-90d1-11e8-8556-4af9bb742a4f.jpg)
![2](https://user-images.githubusercontent.com/34969975/43254879-025c09d8-90d1-11e8-899f-55bd026609d1.jpg)
![3](https://user-images.githubusercontent.com/34969975/43254880-02cf0f1e-90d1-11e8-9eda-d6215357f99d.jpg)


 out, but in version 3.2 the schedule is not built.

**Comment by ghtmtt** [comment]
could you please share your data?

**Comment by Zahar1985** [comment]
[Для статистики.zip](https://github.com/ghtmtt/DataPlotly/files/2231608/default.zip)
[FME_BaumdatenBearbeitet_OGD_1_2015.zip](https://github.com/ghtmtt/DataPlotly/files/2231609/FME_BaumdatenBearbeitet_OGD_1_2015.zip)

**Comment by ghtmtt** [comment]
Some trouble with your data (the codification):

![selection_148](https://user-images.githubusercontent.com/2884884/43263950-02b5da58-90e5-11e8-8207-bd763be115a5.png)

Anyway, I opened the file with Libreoffice, delete some columns and just edited the not encoded characters, reloaded the table in QGIS and I cannot reproduce your problem:

![selection_149](https://user-images.githubusercontent.com/2884884/43264205-b46c24dc-90e5-11e8-94a8-bce0db6a8574.png)

![selection_150](https://user-images.githubusercontent.com/2884884/43264212-b838b4b8-90e5-11e8-8aff-84a32fafcd28.png)

**Comment by MieWinstrup** [comment]
Data Plotly version: 1.5.1.
QGIS version: 3.2.1
OS: Windows

I'm experiencing the same problem - the plots/graphics are not shown:
![image](https://user-images.githubusercontent.com/16276034/44216636-a669d780-a175-11e8-845b-afffd86658e0.png)

The data that I try with is a shapefile with UTF-8 encoding. I have attached the data. I have tried to remove all the fields in the file expect from the id-field to see if it was the danish letters that caused the problem, but it doesn't seem to make any change - the plot is still not shown.

When I look at the messagelog - I can see this:
![image](https://user-images.githubusercontent.com/16276034/44216799-1d06d500-a176-11e8-8cb1-777c52ebdd15.png)

The data that I'm using:
[VEJMIDTE_BRUDT.zip](https://github.com/ghtmtt/DataPlotly/files/2294166/VEJMIDTE_BRUDT.zip)
 
(I have tried with geopackagedata - and its the same problem).

**Comment by MieWinstrup** [comment]
I think it works now!

**Comment by Zahar1985** [comment]
I still did not solve this problem (

**Comment by ghtmtt** [comment]
@MieWinstrup sorry for the delay. I'm trying with your data but randomly I'm able to see the plots. Specifically which columns are you using and which plot do you want to draw?

**Comment by ghtmtt** [comment]
@Zahar1985 very very weird. I'm able to draw the plots with the same variables you are using:

![selection_106](https://user-images.githubusercontent.com/2884884/44587721-16024700-a7b4-11e8-935f-14b3b3b2c969.png)

![selection_107](https://user-images.githubusercontent.com/2884884/44587742-231f3600-a7b4-11e8-9dc9-ca378c280242.png)

Do you mind to have another try?

**Comment by Zahar1985** [comment]
Thanks! It is alright. I with my data in version 3.2.2 !! I tried this with my data in version 3.2.2 !!
![1](https://user-images.githubusercontent.com/34969975/44599144-0992e400-a7de-11e8-90ef-8378f914b487.jpg)

**Comment by MieWinstrup** [comment]
@ghtmtt - sorry for the late reply!!

I'm trying to make a histogram based on the field VEJ_TYPE:

![image](https://user-images.githubusercontent.com/16276034/45109382-b014a880-b13f-11e8-8877-acb559632a23.png)

And the plot is not drawn:
![image](https://user-images.githubusercontent.com/16276034/45109515-1ac5e400-b140-11e8-8fb7-26ee223ccc98.png)

I have also tried with a lot of other data and plottypes - but without any luck.

Could it be a dependency missing in my QGIS-installation? I can check this if you send me some data that works for you?

**Comment by ghtmtt** [comment]
@MieWinstrup mmm I really think that the problem is the workflow. You are trying to plot a numerical histogram of distribution from a string field. Could you try with a numerical field?

**Comment by MieWinstrup** [comment]
This is with a numerical field:
![image](https://user-images.githubusercontent.com/16276034/45110810-9bd2aa80-b143-11e8-9c80-45eba0ebfb6d.png)

But still no plot:
![image](https://user-images.githubusercontent.com/16276034/45110823-a8ef9980-b143-11e8-880c-33c35a8c84c1.png)

**Comment by ghtmtt** [comment]
@MieWinstrup sorry again for the delay. Well if the date you are working with are the same of the zip file you attached in this issue, I cannot replicate the problem:

![selection_165](https://user-images.githubusercontent.com/2884884/45223303-2ab40400-b2b7-11e8-90c7-776cc33e8a75.png)

![selection_164](https://user-images.githubusercontent.com/2884884/45223322-356e9900-b2b7-11e8-8c42-63b1cfc8cba8.png)
