### ISSUE TITLE
Load plot on server

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#80]
Having an additional tab to load/embed the plot on a server (via FTP or other service). Seems feasible

**Comment by nyalldawson** [comment]
Wouldn't this be better suited as a processing tool "upload to FTP"? Then it'd work for other cases and would also avoid cluttering the dataplotly ui.

**Comment by ghtmtt** [comment]
yep, a good idea!

**Comment by nyalldawson** [comment]
So close?
