### ISSUE TITLE
qgis data plotly

### ISSUE THREAD

**Issue by oppia04** [ghtmtt/DataPlotly#81]
when using data plotly there are sometimes problems to visualise the axes titles. e..g long catagory names etc.. The possibility to edit in plotly chart studio is not activated and greyed out. So, how to adapt the graphic? When using the barplot tool from the processing toolbox there is the possibility to change to plotly chart studio while there are less possibilities to adapt the graph.

**Comment by ghtmtt** [comment]
sorry for the delay. Which version of QGIS and Dataplotly are you using? There is the chance to change plot title, x and y axis labels. However not single category names (these are taken from the attribute table)

**Comment by oppia04** [comment]
I am using Qgis 3.2. and Dataplotly 1.6. Yes, I can change the axis title but e.g. when the category names are longer e.g. "_arable fields-not cultivated-123_" there is the need to make the field with the attribitions larger otherwise it will be cut e.g. "_arable fields-no/_"

**Comment by ghtmtt** [comment]
Yes this feature is not implemented (yet). What you can do is create another field in the attribute table with code values instead of longer values. Hopefully I will add this feature in the future.

Closing this issue because is not an issue but a feature request.

Thanks @oppia04

**Comment by ghtmtt** [comment]
if you think this is a blocking feature than you can try to found the feature
