### ISSUE TITLE
[Feature Request] Multi traces with groupby 'categorical' and aggregate with 'operation'

### ISSUE THREAD

**Issue by mazzma12** [ghtmtt/DataPlotly#83]
Hi,

The plugin is great, to add more flexibility one feature I can think of is a `groupby` method to concatenate several traces on the same figure

## example

groupby "data_type" and and aggregate with "sum"  shall produce the equivalent of this :+1: 
```python
import plotly.graph_objs as go
import pandas as pd
from plotly.offline import iplot

import plotly.offline

df = pd.DataFrame([[2, 2, 2, 'A'], [1, 1, 2, 'B'], [1, 1, 2, 'B']], columns=['v1', 'v2', 'v3', 'data_type'])
traces = [go.Scatter(dict(x=key, y=value)) for key, value in df.groupby('data_type').sum()]
```

**Comment by ghtmtt** [comment]
@mazzma12 thanks for sharing your thoughts..

maybe I dont't get exactly what you have in mind. You can already overlap different traces on the same figure. Do you have something different in mind? Could you share a screenshot?

Thanks

**Comment by mazzma12** [comment]
Sorry I should have been clearer in my example . I think this is what I am
looking for, but how do you overlap time series ?

**Comment by ghtmtt** [comment]
you can do it easily. suppose to have the `date` field with time series values and then the `XX` field and the `YY` field.

As shown above you can create as many traces as you want (also overlapping different plot types, e.g. scatterplot and barplot) by keeping the same `date` field as `x` axes and using `XX` and `YY` as y axes.

See https://github.com/ghtmtt/DataPlotly#overlapped-plots for an example screenshot

**Comment by ghtmtt** [comment]
@mazzma12 can I close this issue? Did you solve the problem?

**Comment by ghtmtt** [comment]
ok let's try the following approach. I suppose you have a single layer with all the data, right? Something like:

ID | DateTime | Cl | SO4 |
1 | 01/01/2018 | 12 | 12 |
1 | 02/01/2018 | 10 | 20 |
1 | 03/01/2018 | 05 | 60 |
2 | 01/01/2018 | 02 | 56 |
...

it this right? If yes, I'm understanding you want to filter the IDs in some way? If yes, is the field calculator not enough? 

If this is not solving the problem, please share a piece of your data so we work on it together and find a solution :)

**Comment by ghtmtt** [comment]
ping @mazzma12

**Comment by mazzma12** [comment]
Will check during the WE

**Comment by Kapanther** [comment]
I know this is closed. But just ran into this road block myself.

I have about 15 different ID locations i wanted to overlay on the same graph. But i needed them to group by based on the ID attribute. Not really possibly without splitting the vector layers and overlapping the plots.

A group by plot would be amazing

![image](https://user-images.githubusercontent.com/12637127/56007064-b775e300-5d1a-11e9-8b10-2ec2a0d30b53.png)


Then stuff like this could be generated automatically.

![image](https://user-images.githubusercontent.com/12637127/56006970-4f270180-5d1a-11e9-9310-436bbf14ce1c.png)

**Comment by ghtmtt** [comment]
HI. Yes the behavior you are describing is not currently immediately possible. You should filter manually the values by adding an expression FOR EVERY plot you want to show.
